GoogleCloudPlatform/oss-test-infra

- prow/cert-manager.yaml
Woot PR number 1!
Corresponds to https://github.com/kubernetes/test-infra/pull/10813
/assign @krzyzacy
> Bump cert-manager to version 'v0.5.2' to pick up bug fixes.

- prow/plugins.yaml
Integrate prow with gke-vault-demo
> Add gke-vault-demo

- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
- prow/plugins.yaml
> update oss-prow, add more plugins

- prow/cluster.yaml
- prow/config.yaml
also added some dummy jobs to validate the secret
cc @hopkiw @rofuentes
> add gcp-guest cluster into oss-prow build clusters

- prow/cluster.yaml
(deployed, watch crier for a bit)
> bump oss-prow, add build-cluster to deck, report on github

- prow/plugins.yaml
Just adding additional plugin for our repository. Job config is in #13
> Add plugins for osconfig repository

- prow/cluster.yaml
- prow/config.yaml
- prow/plugins.yaml
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> GCP-guest updates

- prow/cluster.yaml
copy-pasta inherited from https://github.com/kubernetes/test-infra/blob/master/prow/cluster/tide_rbac.yaml
/assign @hopkiw @cjwagner
> add rbac for tide

- prow/cluster.yaml
> add --job-config-path for hook

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> fix wrong indentation for the gcp-guest config

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
this should add logging and spyglass/gubernator links
> decorate presubmit jobs

- prow/cluster.yaml
(I'm not sure if `--oauth-url=/github-login` is correct or not)
> add tide/hook urls to deck

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Update with abs path to allow decoration and functional test at the same time..
> update command paths

- prow/cluster.yaml
> fix oauth secret name

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> fix indent for osconfig-agent-build

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
this image is not go based, so correct the path
> correct path for gcp-guest agent build

- prow/config.yaml
> Enable spyglass for oss-prow

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
(Should've caught #31, fyi @iamsubratp)
> make presubmit takes in job-config-path as well

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
these three should be generic for all of our go repos
> go presubmits for guest-agent repo

- prow/cluster.yaml
- prow/config.yaml
Also switch spyglass to be default: https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/33/pull-prow-config-validate/1126223563888529408
> Fix deck rbac, bump prow to latest

- prow/config.yaml
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Add prev also for guest-logging-go

- prow/plugins.yaml
> enable review_acts_as_lgtm for this repo

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Adds a presubmit that runs the selinux module validation script.
> add selinux module check

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Update modcheck path

- OWNERS
/assign @krzyzacy @michelle192837
> Add oncall to OWNERS

- prow/bump.sh
- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
* Also check in bump script
/assign @michelle192837 @katharine
> Bump prow to v20190827-256e5bbca

- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
This reverts commit 8b09183274e1964af39bf3d65bce9702fb7d7bb4.
Accidentally pushed to master, reverting.
> Revert "Update prow to v20190830-56bd52b0e."

- prow/pj-on-kind.sh
Useful tool for running local ProwJobs. 👍 
/assign @cjwagner @fejta
> Add "pj-on-kind.sh" script

- OWNERS
Seems reasonable since I will be on-call soon and have been making incremental prow improvements here as well as adding `build` cluster(s).
> Add clarketm to OWNERS

- README.md
- prow/README.md
Copied from another Prow repository with a similar bumping strategy
> Add README to Prow Directory

- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Adds the first job to the testgrid build cluster
> Enable Testgrid Testing

- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
Change to cluster due to possible credential issue with testgrid build cluster
Hanging merge at https://github.com/GoogleCloudPlatform/testgrid/pull/9
> Change cluster

- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/assign @fejta @michelle192837 @Katharine @cjwagner
> Update Prow to v20190918-7672de02b

- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Update Prow to v20190919-01001ae61

- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Update Prow to v20190920-d724a578b

- prow/bump.sh
- prow/cluster.yaml
- prow/config.yaml
- prow/grandmatriarch_default.yaml
- prow/grandmatriarch_test-pods.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/assign @michelle192837 @clarketm @Katharine 
https://github.com/kubernetes/test-infra/compare/cb71f84e1...a9e239ad8
> Update prow to v20190927-a9e239ad8

- prow/cluster/cluster.yaml
- prow/cluster/grandmatriarch_default.yaml
- prow/cluster/grandmatriarch_test-pods.yaml
- prow/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
This reverts commit 42c2a1929e1fb94975f2f7de24287093533c4b75.
Lots of problems.
> Revert "Update prow to v20190927-a9e239ad8"

- prow/config.yaml
> Add "preset-service-account" preset

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
* packagebuild postsubmit for all package providing repos
* gobuild/test for guest-test-infra
> gcp guest add jobs

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
I copied the `oauth-token` secret into the test-pods namespace (`cluster: test-infra-trusted`).
> Add a periodic job to autobump Prow.

- prow/cluster/cluster.yaml
- prow/cluster/grandmatriarch_default.yaml
- prow/cluster/grandmatriarch_test-pods.yaml
- prow/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/assign @BenTheElder @cjwagner @michelle192837
> Update prow to v20191009-0492f1d6e

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Correct gcloud-in-go image

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Fake change to trigger deploy

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/hold
until https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-test-infra-push-prow/1182099210011414531 completes (and confirm I got the tag right).
/assign @fejta
> Bump autobump.

- prow/bump.sh
Not the most advanced fix, but it works
/assign @BenTheElder
> Only bump prow images

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Dates are in UTC :man_facepalming: 
/assign @fejta
> Fix autobump version typo.

- prow/plugins.yaml
/assign @cjwagner @chases2 
Would like `/close` etc to wokr
> Enable lifecycle plugin

- prow/plugins.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
fixes https://github.com/GoogleCloudPlatform/oss-test-infra/issues/126
/assign @fejta
> Fix prow config validation.

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
add package builder presubmits for guest-agent and guest-oslogin repos
> packagebuild for guest-agent and guest-oslogin

- prow/cluster/cluster.yaml
copied from upstream, fixes #160
> update sinker and deck rbac

- prow/config.yaml
> Authorize rerun using GoogleCloudPlatform org

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
This email is correctly associated with CLAs, and doesn't require an override to merge the PRs it generates.
Addresses #157 
/assign @fejta
> Update Robot Email Address

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Adds an optional presubmit test to check TestGrid configurations
Also changed YAML spacing to be in-line with rest of the file
> Add TestGrid Presubmit Test

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- testgrid/config.yaml
> TestGrid Dashboard Fix

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Signed-off-by: Xuyang Tao <taoxuy@google.com>
> setup esp-v2 oss basic prowjob

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
bucket name was wrong for these jobs
> Fix GCP guest upload bucket

- prow/prowjobs/GoogleCloudPlatform/esp-v2/OWNERS
/assign @TAOXUY 
Other users should be added to these jobs, as appropriate.
> Add OWNERS to GCP/esp-v2 Prow Jobs

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
add googet packages for guest agent pre and post builds
> build guest-agent googet packages

- prow/Makefile
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
> Use workload-identity to deploy prow

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
* packagebuild was not being kicked off
* update run_if_changed params to match patterns others are using
* use presets to simplify common fields
> update run_if_changed for gcp-guest

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
Auto-apply testgrid cluster changes.
> Add testgrid-deployer service account

- prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/OWNERS
- prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml
/assign @BenTheElder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudplatform/oss-test-infra/229)
> Add Prow config for GoogleCloudPlatform/k8s-cloud-provider

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
ref https://github.com/GoogleCloudPlatform/testgrid/issues/78
> Add missing --confirm flag

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Uses new dir arg to gobuild/gotest/gocheck added in guest-test-infra#21
> add go presubmits for clitools

- prow/cluster/cluster.yaml
... also move to v1
/cc @fejta
> switch tide to clusterrole so it can create pods in other namepsaces

- prow/Makefile
> Apply build cluster service accounts

- prow/cluster/cluster.yaml
ref #245 
/assign @BenTheElder 
Maybe this will make it apply things?
> Deployments are now v1

- prow/cluster/cluster.yaml
/assign @BenTheElder 
ref https://github.com/GoogleCloudPlatform/oss-test-infra/issues/245
> Add deployment selector

- prow/config.yaml
- prow/plugins.yaml
* add new repo compute-image-tools
* add blunderbuss to guest repos
> add new repos for guest OS

- prow/cluster/cluster.yaml
/assign @cjwagner @Katharine 
ref https://github.com/GoogleCloudPlatform/oss-test-infra/issues/245
> Namespace all objects

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
This reverts commit 1523be8563657692fbf543f28289b9861b2c3869.
> Revert "Revert "Use workload identity for esp-v2 jobs""

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
This reverts commit efc6825d78fbca0aa7982431e405ca69e6ca1692.
> Revert "Revert "Revert "Use workload identity for esp-v2 jobs"""

- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
/assign @michelle192837 @chases2 
Will unblock https://github.com/GoogleCloudPlatform/testgrid/pull/92
> Use image to choose bazel version in testgrid repo

- prow/cluster/cluster.yaml
/assign @clarketm @TAOXUY 
/hold
After jobs that set `cluster: espv2` will schedule in that cluster.
> Use updated kubeconfig

- prow/cluster/cluster.yaml
/assign @michelle192837 
Also have tide track history between restarts
> Bind crier/deck/tide service accounts to oss-prow@oss-prow.iam.gserviceaccount.com

- prow/cluster/cluster.yaml
- prow/config.yaml
/assign @michelle192837 @Katharine
> Point to https://oss-prow.knative.dev/

- prow/cluster/cluster.yaml
> Annotate service account, not service

- prow/cluster/cluster.yaml
/assign @Katharine @michelle192837
> Use a new cert for oss-prow.knative.dev

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Create deploy prod and canary testgrid jobs

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/assign @cjwagner @michelle192837 @chases2
> Use more recent gcloud-bazel image to deploy testgrid

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
> Upload oss-prow results into resultstore.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
for https://github.com/GoogleCloudPlatform/oss-test-infra/pull/177
> checkconfig: exclude warning = non-decorated-jobs

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
- testgrid/config.yaml
Otherwise, we cannot modify our jobs due to the validations added in #267
> Add esp-v2 to testgrid

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
> Add presubmit and continuous coverage jobs

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Use newer resultstore exporter image

- prow/cluster/cluster.yaml
- prow/cluster/grandmatriarch_default.yaml
- prow/cluster/grandmatriarch_test-pods.yaml
- prow/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Reverts GoogleCloudPlatform/oss-test-infra#310
deck is broken.
> Revert "Bump prow from v20200228-31c76444e to v20200314-12f848798"

- prow/cluster/cluster.yaml
> Update secret with new redirect URL

- prow/create-build-cluster.sh
> Fix indentation in create-build-cluster.sh

- prow/config.yaml
/assign @michelle192837 @cjwagner
> Migrate to rerun_auth_configs

- prow/create-build-cluster.sh
/assign cjwagner 
See https://github.com/knative/test-infra/pull/1910 for usage
> create-build-cluster.sh works for other Prow instance as well

- prow/cluster/ghproxy.yaml
> Deploy and use ghproxy for Prow components.

- prow/cluster/ghproxy.yaml
> Fix ghproxy deployment apiversion.

- prow/cluster/cluster.yaml
Depends on 
/hold
/assign fejta
> Switch Prow components to use ghproxy.

- prow/cluster/cluster.yaml
- prow/cluster/ghproxy.yaml
- prow/cluster/grandmatriarch_default.yaml
- prow/cluster/grandmatriarch_test-pods.yaml
- prow/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Reverts GoogleCloudPlatform/oss-test-infra#349
> Revert "Bump prow from v20200417-a6017ee5b to v20200427-baaf248ed"

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Contains `python3-distutils`
Ref: GoogleCloudPlatform/esp-v2#165
> [ESPv2] Update prow images for Envoy update

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Missed these in the previous PR due to a different image name.
Ref GoogleCloudPlatform/esp-v2#165]
> [ESPv2] Update coverage images

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
> Make en-server presubmit report.

- prow/oss/cluster/cluster.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
This reverts commit 232e35df0e06874cefa38f63331f6c4bb46fbaa5.
This reverts PR https://github.com/GoogleCloudPlatform/oss-test-infra/pull/387
> Revert "Bump prow from v20200608-16190316cf to v20200609-2d17640dc1"

- prow/Makefile.gcloud.mk
- prow/bump.sh
- prow/knative/Makefile
- prow/knative/README.md
- prow/knative/cluster/100-namespace.yaml
- prow/knative/cluster/200-cpu-limitrange.yaml
- prow/knative/cluster/200-memory-limitrange.yaml
- prow/knative/cluster/300-crds.yaml
- prow/knative/cluster/301-rbac.yaml
- prow/knative/cluster/302-gce-ssd-retain_storageclass.yaml
- prow/knative/cluster/400-crier.yaml
- prow/knative/cluster/400-deck.yaml
- prow/knative/cluster/400-ghproxy.yaml
- prow/knative/cluster/400-hook.yaml
- prow/knative/cluster/400-horologium.yaml
- prow/knative/cluster/400-ingress.yaml
- prow/knative/cluster/400-plank.yaml
- prow/knative/cluster/400-sinker.yaml
- prow/knative/cluster/400-tide.yaml
- prow/knative/cluster/500-needs-rebase.yaml
- prow/knative/cluster/500-status-reconciler.yaml
- prow/knative/cluster/build/200-cpu-limitrange.yaml
- prow/knative/cluster/build/200-memory-limitrange.yaml
- prow/knative/cluster/build/301-rbac.yaml
- prow/knative/cluster/build/400-boskos-deployment.yaml
- prow/knative/cluster/build/400-boskos-janitor.yaml
- prow/knative/cluster/build/400-boskos-metrics.yaml
- prow/knative/cluster/build/400-boskos-reaper.yaml
- prow/knative/cluster/build/400-boskos.yaml
- Copy/paste knative prow deployments as well as build cluster deployments configs here, so that auto-bump is handled here
- Add Makefile for manual deployments
- Add README
Postsubmit updating job will be added in knative/test-infra repo later
> Add knative prow configs

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/hold
Will need to give the service account permission to do so
/assign @cjwagner @fejta 
/cc @chizhg
> Add postsubmit job updating knative prow deployment

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
> Add a canary job testing build cluster for apollo server repo

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
It had fulfilled the purpose, clean it up now
> Delete apollo server canary job

- prow/oss/plugins.yaml
> respect github status in reviewer assignment

- prow/oss/cluster/cluster.yaml
> Update kubeconfig to 'oss-config-20200630' to include knative-prow-trusted cluster.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Revert of https://github.com/GoogleCloudPlatform/oss-test-infra/pull/406
> Revert addition of Knative Prow autobump job.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Also update autobump image to latest to take in the fix from https://github.com/kubernetes/test-infra/pull/18126
/cc @cjwagner
> Revert "Revert "Add auto bump job for knative prow configs""

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
corollary to GoogleCloudPlatform/guest-diskexpand#3
> build disk expand for el8

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Presubmit checking knative prow configs

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Working on creating testgrid specific variants of these images for the future
https://github.com/kubernetes/test-infra/blob/2771dcbd50357dce0018cce74e91cfaa009273c4/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L162
https://github.com/kubernetes/test-infra/blob/2771dcbd50357dce0018cce74e91cfaa009273c4/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L44
> Update testgrid image to tags with bazel 3.0.0 installed.

- prow/knative/cluster/301-rbac.yaml
- prow/knative/cluster/400-deck.yaml
- prow/knative/cluster/400-hook.yaml
- prow/knative/cluster/400-tide.yaml
> More knative prow explicit namespaces

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
> [ESPv2] Add e2e jobs for `gcloud_build_image` test

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
> Add Twilio credentials

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
- prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
> Move Twilio credentials from en-server to en-verification-server job

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
Run performance test more frequently so that we can get a better sense of moving average changes as in: https://mako.dev/benchmark?benchmark_key=4790091207671808
/cc @sethvargo @MushuEE
> En server: run performance test every 3 hours

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
The old image blocks deploying anthos.
> Update kubekins version

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Hopefully it will trigger in the next 15 minutes...
> [ESPv2] Temporarily increase continuous test frequency

- prow/knative/cluster/build/400-boskos-deployment.yaml
- prow/knative/cluster/build/400-boskos-janitor.yaml
- prow/knative/cluster/build/400-boskos-metrics.yaml
- prow/knative/cluster/build/400-boskos-reaper.yaml
To fix the janitor issue in https://github.com/kubernetes-sigs/boskos/issues/37
> Update boskos to the latest

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
ref: https://github.com/kubernetes/test-infra/pull/18895#issuecomment-678555526
> Fix misspelling

- prow/oss/cluster/cluster.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Reverts GoogleCloudPlatform/oss-test-infra#485
> Revert "Bump oss-prow from v20200825-967ee0e48b to v20200831-223e625607"

- prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
> En verification server: add canary e2e test job

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
> Update prow image to 20200903

- prow/knative/cluster/400-plank.yaml
> Remove deprecated plank arg

- prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
Key server terraform smoke test worked: https://oss-prow.knative.dev/?job=ci-en-server-terraform-smoke, adding for verification server as well
/assign @sethvargo
> En verification server: Continuously running terraform smoke test

- prow/oss/cluster/sinker.yaml
See https://github.com/kubernetes/test-infra/issues/19382 for context.
> Update sinker permissions.

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/plank.yaml
- prow/oss/cluster/sinker.yaml
> Update oss-prow kubeconfig to config-20201002.

- prow/knative/config.yaml
Ref: https://github.com/knative/pkg/issues/1785
> set tide to ignore unknown branch status

- prow/oss/cluster/deck.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/tide.yaml
All exposed ports need to have name
/cc @cjwagner
> Naming all ports exposed

- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/OWNERS
- prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
Part of onboarding Secret Manager CSI Driver as part of https://github.com/GoogleCloudPlatform/oss-test-infra/issues/474
> Add GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp Prow job

- prow/oss/Makefile
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Make oss-prow deploy job deploy the monitoring stack.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Dummy change to test oss-prow deploy job.

- prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
:latest includes kubectl per https://github.com/GoogleCloudPlatform/cloud-sdk-docker
> Use :latest instead of :alpine base image

- prow/oss/cluster/monitoring/mixins/Makefile
Add GO bin to PATH in the context of makefile
> Fix monitoring make target

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
These images have `lcov` installed.
> [ESPv2] Update coverage job images

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Made a typo when copy pasting...
> [ESPv2] Fix incorrect image name

- prow/oss/cluster/monitoring/grafana_deployment.yaml
- prow/oss/cluster/monitoring/prometheus_operator_deployment.yaml
- prow/oss/cluster/monitoring/prometheus_operator_rbac.yaml
- prow/oss/cluster/monitoring/prometheus_rbac.yaml
- prow/oss/cluster/monitoring/prow_prometheus.yaml
- prow/oss/cluster/monitoring/prow_servicemonitors.yaml
There is a mix of indent exist/not before yaml list elements, make them consistent by removing the indentation
> YAML cleanup: consistent indentation before list elements

- prow/prowjobs/google/exposure-notifications-server/en-server.yaml
It'll be broken once https://github.com/google/exposure-notifications-server/pull/1110#issuecomment-715366336 merged
> EN: update key server jobs scripts path

- prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
- prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
/assign @fejta @michelle192837
> Prow alert emails subject contains prow instance name

- prow/knative/cluster/400-plank.yaml
- prow/knative/cluster/400-prow-controller-manager.yaml
- prow/oss/cluster/plank.yaml
- prow/oss/cluster/prow-controller-manager.yaml
/hold
/assign @chaodaiG @chases2
> Switch oss and knative from plank to prow-controller-manager

- prow/knative/cluster/monitoring/grafana_deployment.yaml
- prow/oss/cluster/monitoring/grafana_deployment.yaml
As done in https://github.com/kubernetes/test-infra/pull/19692
> Update grafana to 6.7.4

- prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml
Add torvalds/master branch to Prow config so that presubmit runs on it
as well.
> Add torvalds/master branch to Prow config

- prow/knative/config.yaml
- prow/knative/plugins.yaml
> Knative prow begins monitoring knative-prow-robot/test-infra repo

- prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
> Use custom mirror of postgres image in tests

- prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml
> Use custom redis image too

- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
See kubernetes/test-infra#19906 for more
context. Applying a similar change to our other Prow instances.
> Update rbac for oss-prow.

- prow/knative/cluster/500-cherrypicker.yaml
Configure cherrypicker plugin for Knative Prow
Fixes: https://github.com/knative/test-infra/issues/2536
> Configure cherrypicker plugin for Knative Prow

- prow/knative/cluster/400-crier.yaml
- prow/knative/cluster/400-deck.yaml
- prow/knative/cluster/400-hook.yaml
- prow/knative/cluster/400-horologium.yaml
- prow/knative/cluster/400-sinker.yaml
- prow/knative/cluster/400-tide.yaml
- prow/knative/cluster/build/400-boskos-deployment.yaml
- prow/knative/cluster/build/400-boskos-janitor.yaml
- prow/knative/cluster/build/400-boskos-reaper.yaml
> Changing cluster Deployments to "apps/v1"

- prow/oss/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
We are no longer using this service
> Remove resultstore service account and jobs.

- prow/knative/cluster/monitoring/Makefile
- prow/oss/cluster/monitoring/Makefile
> Automatically deploy prow monitoring secrets post submit

- prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
- prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
> Prow alerts send to test-infra oncall instead of engprod oncall

- prow/oss/cluster/monitoring/grafana_expose.yaml
Revert #661 
The above PR failed due to loadbalander creation failure caused by an internal error, revert for now while investigating for the resolution
> Revert "Expose prow monitoring dashboard"

- prow/prowjobs/kubeflow/OWNERS
- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Migrating the first presubmit test to verify the setup
> Migrate first Kubeflow presubmit test to oss prow

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
> Update kubeflow-presubmits.yaml, rename test

- prow/prowjobs/kubeflow/OWNERS
- I recently joined a team in Google working on parts of Kubeflow. Was told to add myself to the list.
> added xiyue as kubeflow owner

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
> Correct kubeflow build cluster name

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
> fix(kubeflow): add decorate true

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Tests copied from https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-presubmits.yaml.
Only added kubeflow-pipeline tests, others will be moved later.
> test(kubeflow): add KFP presubmit tests as optional

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
made a mistake, forgot to rename some of the tests
> fix(kubeflow): rename kfp presubmits

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Upgrade generic_autobump to v20210125-7ba72b3

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Update testgrid autobump to v20210126-f503f3e

- prow/oss/config.yaml
- prow/oss/plugins.yaml
- prow/prowjobs/kubeflow/kubeflow-periodics.yaml
- prow/prowjobs/kubeflow/kubeflow-postsubmits.yaml
- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
This PR should be merged at the same time as https://github.com/kubernetes/test-infra/pull/20553.
> test(kubeflow): enable tests & tide for kubeflow/pipelines

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
> test(kubeflow): rename kfp tests to remove v2 suffix

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
Part of kubernetes/test-infra#14343
> test(kubeflow): rename kfp tests to be exactly like before

- prow/prowjobs/kubeflow/kubeflow-presubmits.yaml
> test(kubeflow): fix kfp tests

- prow/oss/cluster/monitoring/grafana_expose.yaml
This reverts commit 53dabe6f1bca1ee2c9e83168b8be5634905c7aa8.
The blocking issue that prevented loadbalancer creation seemed resolved, trying it again
> Revert "Revert "Expose prow monitoring dashboard""

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
/assign @chases2 
https://play.golang.org/p/UBRAEDvGSq1
> Only push images when non-cluster files change

- prow/oss/cluster/monitoring/mixins/grafana_dashboards/ghproxy.jsonnet
- prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
- prow/oss/cluster/monitoring/mixins/lib/config_util.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/ghproxy_alerts.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/stale_alerts.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/tide_alerts.libsonnet
Includes:
- Major defaulting improvements.
- Improved ghproxy dashboards.
- Stale image alert bug fix.
> OSS prow monitoring: update based on all recent improments from k8s prow monitoring stack

- prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
Fix a couple of errors introduced in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/678
> Fix prow monitoring stack

- prow/knative/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
- prow/oss/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
See https://github.com/kubernetes/test-infra/pull/20744
> Adjust prow components absent alert threshold from 5 to 10 minutes

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
/assign @zijianjoy 
Part of https://github.com/kubeflow/pipelines/issues/5152
> test(kubeflow): increase timeout of kubeflow-pipelines-postsubmits.yaml to 2h

- prow/knative/config.yaml
- prow/knative/plugins.yaml
/hold
This needs the following to land: 
- new teams: https://github.com/knative/community/pull/479
- net-contour: DONE
- net-certmanager: https://github.com/knative-sandbox/net-certmanager/pull/185
- net-ingressv2: https://github.com/knative-sandbox/net-ingressv2/pull/7
- net-http01: https://github.com/knative-sandbox/net-http01/pull/192
- net-istio: https://github.com/knative-sandbox/net-istio/pull/525
- net-kourier: https://github.com/knative-sandbox/net-kourier/pull/453
> Use CODEOWNERS file for approvals in net-*

- prow/knative/config.yaml
- prow/knative/plugins.yaml
/assign @chaodaiG @chizhg 
/hold
With the exception of kperf all of the CODEOWNERS PRs have merged.  I'm going to prepare the test-infra PR now as well.
> Switch the sample and productivity repos over to CODEOWNERS

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
Part of https://github.com/kubeflow/pipelines/issues/5178
/assign @numerology @chensun
> test(kubeflow): fix kubeflow-pipelines-postsubmits.yaml

- prow/knative/config.yaml
- prow/knative/plugins.yaml
/hold
cc @rhuss @lionelvillard
/assign @chizhg @chaodaiG
> Move the knative-sandbox org to CODEOWNERS

- prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
- testgrid/config.yaml
> test(kubeflow): add testgrid config

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Part of https://github.com/kubeflow/pipelines/issues/5236
Addresses https://github.com/kubeflow/pipelines/issues/5236#issuecomment-790255936
> test(kfp): add run_if_changed config for mkp presubmit

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> add jobs for new guest repos

- OWNERS
Adding myself to OWNERS for oncall
> Add mpherman2 to OWNERS

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Fixes: https://github.com/GoogleCloudPlatform/oss-test-infra/issues/730
> Update knative config validate job to use main branch

- README.md
- prow/oss/README.md
- prow/oss/onboarding.md
@chaodaiG wrote these docs, I'm just moving them here and making some minor additions.
> Add oss-prow onboarding docs.

- prow/knative/cluster/400-deck.yaml
- prow/oss/cluster/deck.yaml
This will expose the parsed plugin configuration at https://oss-prow.knative.dev/plugin-config and https://prow.knative.dev/plugin-config
/hold
> Serve plugin config from Deck.

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Part of https://github.com/kubeflow/pipelines/pull/5337
> test(kubeflow): kubeflow-pipelines-v2-samples-test

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Part of https://github.com/kubeflow/pipelines/pull/5337
> test(kubeflow): enable kubeflow-pipelines-samples-v2 test

- prow/prowjobs/kubeflow/internal-acls/kubeflow-internal-acls.yaml
Part of https://github.com/kubeflow/internal-acls/issues/346
> test(kubeflow): set up presubmit for kubeflow/internal-acls

- prow/prowjobs/kubeflow/internal-acls/kubeflow-internal-acls.yaml
> test(kubeflow): add missing decorate=true to kubeflow-internal-acls test

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Test config for https://github.com/kubeflow/pipelines/pull/5390
> test(kubeflow): add kubeflow-pipelines-manifests test

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
kfp samples v2 test should trigger on sample change
> test(kubeflow): kfp samples v2 test should trigger on sample change

- prow/knative/cluster/301-rbac.yaml
- prow/oss/cluster/horologium.yaml
https://github.com/kubernetes/test-infra/pull/21760
> Horologium: update RBAC with newly required permission

- prow/knative/config.yaml
> Allow PRs created by knative-prow-updater-robot to be automatically merged

- prow/oss/cluster/deck.yaml
> Revert oss-prow deck to v20210412-ed35ec0cee

- prow/oss/cluster/deck.yaml
/assign @chaodaiG @cjwagner 
Includes https://github.com/kubernetes/test-infra/pull/21855
> Patch deck to v20210419-68a26a452c

- prow/oss/cluster/cluster.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/config.yaml
Depends on #781 , plus not deploy late in the day
/hold
> Add private deck deployment to oss prow

- prow/oss/config.yaml
This is Chao's personal org for experimenting inrepoconfig and private deck
> Onboarding chaotoppicks org: setting up webhook and accept invitation

- prow/oss/config.yaml
> Opt testgrid into automatic webhook management

- prow/oss/config.yaml
Alphabetized and added an entry for `esp-v2` repo.
/cc @TAOXUY
> Configure managed webhooks for esp-v2 repo.

- prow/oss/cluster/cluster.yaml
> Add back private deck ingress #3

- prow/oss/cluster/kubernetes_external_secrets.yaml
> Add external secret from build cluster for looker-private

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
/hold
depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/816
> Add build cluster kubeconfig for looker-private

- prow/oss/config.yaml
> Fix Looker GCS bucket name.

- prow/oss/config.yaml
> Fix a typo in private org name

- prow/oss/cluster/deck.yaml
> Fix Deck RBAC by updating service account ref.

- prow/oss/cluster/deck_private_deployment.yaml
> Make Tide data available to private Deck.

- prow/oss/cluster/monitoring/grafana_expose.yaml
I'll delete the ingress from the cluster manually.
> Temporarily disable monitoring ingress.

- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_private_deployment.yaml
> Make private deck HA and add readiness probes to public deck.

- prow/oss/config.yaml
- prow/oss/plugins.yaml
> Restrict to only helltool repo from looker org

- prow/oss/config.yaml
> Configure private tide target_url for private looker repo.

- prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
> Add back job config checker job for looker/helltool

- prow/oss/plugins.yaml
- prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
> Make helltool Prow config validation only run on config changes and disable size plugin.

- prow/oss/config.yaml
* Add k8s-cloud-provider to config to enable tide
> Add GoogleCloudPlatform/k8s-cloud-provider to tide

- prow/knative/config.yaml
- prow/oss/config.yaml
> Enable Google Analytics for both OSS and Knative Prow.

- prow/oss/plugins.yaml
/cc @Jeffwan @gaocegege @Bobgy
> Require self approval for kubeflow training operators

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
> Add build cluster kubeconfig for elcarro

- prow/oss/create-build-cluster.sh
add default control plane SAs
default GCS_BUCKET to be team specific
> Fix oss prow onboarding bugs

- prow/oss/config.yaml
Give more time for autosclaing nodes
> Increase pod unscheduled timeout to 5 minutes

- prow/oss/config.yaml
> Enable html lens on OSS Prow.

- prow/oss/cluster/kubernetes_external_secrets.yaml
So that oss prow can post messages on knative slack for knative prow related activities
> Add knative slack token as a secret in oss prow

- OWNERS
I have been in a different oncall and inactive here / overloaded elsewhere
> move bentheelder to emeritus

- prow/oss/create-build-cluster.sh
> Clarify requirement and expected value of GITHUB_FORK_URI.

- prow/oss/config.yaml
fixes https://github.com/GoogleCloudPlatform/blueprints/issues/6
> Onboard  GoogleCloudPlatform/blueprints repo

- prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
Follow up to https://github.com/GoogleCloudPlatform/oss-test-infra/pull/900
cc @bharathkkb
> Add a checkconfig presubmit to validate GoogleCloudPlatform/blueprints in repo config.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
> Delete update-monitoring job

- prow/knative/config.yaml
Fixes: https://github.com/knative/test-infra/issues/2832
> expand the teams that can use the prow ui

- prow/oss/plugins.yaml
> Make lgtm sticky for googlers in oss-test-infra and testgrid

- prow/oss/cluster/sub.yaml
So that it can clone from inrepoconfig
> OSS prow sub: add github token

- prow/oss/cluster/sub.yaml
> Add missing RBAC for sub

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
Corresponding PR on KFP: https://github.com/kubeflow/pipelines/pull/6227
> test: fix kfp periodic cleanup job by changing image.

- prow/oss/cluster/sub.yaml
This should help mitigate a performance bottleneck with cloning large repos to get inrepo config.
cc @2nd-half
> Increase Sub replicas from 1 to 10.

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
a lot of the times, the two heavy-load tests are not necessary at all
limit them with run_if_changed
> test(kubeflow): add run_if_changed for kubeflow-pipeline-{e2e,sample,upgrade}-test

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> add cit-periodics

- OWNERS
Ethan, Travis and Aaron are not currently contributing to this repo on a regular basis
> Cleanup OWNERS files.

- prow/oss/terraform/modules/alerts/main.tf
> Add terraform config for a predicted-gh-rate-limit-exhaustion alert.

- prow/oss/terraform/Makefile
- prow/oss/terraform/modules/alerts/main.tf
This has just be `terraform apply`ed
> Terraform validation and fixes to gh rate limit exhaustion prediction query.

- prow/oss/terraform/modules/alerts/main.tf
the previous absent_for condition was not applicable because the result was gauge value
> Fixing heartbeat job stale alert

- prow/oss/terraform/modules/alerts/main.tf
by the way addressing previous comment from https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1028
> Fix webhook missing alert

- prow/oss/cluster/build/serviceaccounts.yaml
Start by declearing a presubmit k8s SA.
> Add serviceaccounts.yaml file to build cluster.

- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml
ref https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1036 https://github.com/GoogleCloudPlatform/testgrid/pull/637
> Use presubmits SA on the testgrid presubmit

- prow/oss/config.yaml
> Configure tenantIDs for private prowjobs

- prow/oss/config.yaml
> Jobs in test-infra-trusted cluster use WI by default

- prow/oss/cluster/sub.yaml
https://github.com/kubernetes/test-infra/pull/23394
> Bumping sub with hot fix for set origin url

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
> Add build cluster kubeconfig for looker-16

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
> Add build cluster kubeconfig for looker-32

- prow/oss/cluster/deck_private_deployment.yaml
/assign @cjwagner @chaodaiG 
/hold
> Switch Deck Private instance from hidden only to tenantID

- prow/oss/cluster/deck_private_deployment.yaml
Reverts GoogleCloudPlatform/oss-test-infra#1079
> Revert "Switch Deck Private instance from hidden only to tenantID"

- prow/oss/cluster/cluster.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
> Add deployment for blueprints deck

- prow/oss/cluster/cluster.yaml
> Add blueprints managed cert to new ingress

- prow/oss/cluster/cluster.yaml
> Change static ip for blueprints ingress

- prow/oss/cluster/deck_blueprints_deployment.yaml
> Add redirect to blueprints deck

- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/kubernetes_external_secrets.yaml
> Add redirect to blueprints oauth proxy

- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/kubernetes_external_secrets.yaml
> Create new blueprints oauth secrets for new oauth app

- prow/oss/cluster/cluster.yaml
> Update ingress apiversion to networking.k8s.io/v1

- prow/oss/cluster/cluster.yaml
Reverts GoogleCloudPlatform/oss-test-infra#1110
> Revert "Update ingress apiversion to networking.k8s.io/v1"

- prow/oss/config.yaml
/hold
/assign @chaodaiG @cjwagner @bharathkkb
> Add blueprints tenantID

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/gerrit.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/horologium.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
- prow/oss/cluster/sub.yaml
- prow/oss/cluster/tide.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Reverts GoogleCloudPlatform/oss-test-infra#1135
> Revert "Update oss-prow to v20210917-ee1e7c845b"

- prow/knative/cluster/build/500-kubernetes-external-secrets_crd.yaml
- prow/knative/cluster/build/500-kubernetes-external-secrets_deployment.yaml
- prow/knative/cluster/build/500-kubernetes-external-secrets_rbac.yaml
Updated following https://github.com/external-secrets/kubernetes-external-secrets#install-with-kubectl
fixes: https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1061
> knative build cluster: update external secret to 8.3.0

- prow/oss/terraform/README.md
- prow/oss/terraform/modules/alerts/boskos/main.tf
- prow/oss/terraform/modules/alerts/boskos/variables.tf
boskos doesn't exist in oss-prow, this module can be imported by other projects for monitoring boskos resources
> Add boskos alerts

- prow/oss/cluster/sub.yaml
> Configure a more appropriate rolling update for Sub.

- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
I plan to delete and disable the old token once this is complete.
> Complete rotation of Prow bot token.

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Fixes: https://github.com/kubeflow/pipelines/issues/6669
> Update kubeflow-pipelines-presubmits.yaml to test TFX with Python 3.7

- prow/oss/config.yaml
- prow/oss/plugins.yaml
Part of https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1171
This is used for piloting/experimenting GitHub app authentication, will be cleaned up afterwards
> Onboard testing org chaotoppicks on OSS prow

- prow/oss/cluster/crier-ghapp.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/hook-ghapp.yaml
- prow/oss/cluster/hook.yaml
#1246 had been proved to be working, switching all over now is not super risky
/hold
> GoogleCloudPlatform all switch over to use GitHub app

- prow/oss/cluster/crier-ghapp.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/hook-ghapp.yaml
- prow/oss/cluster/hook.yaml
Prow app is already installed in kubeflow repos
> Migrate kubeflow org to use GitHub app for authenticating

- .prow/presubmits.yaml
- prow/oss/oss-autobump-config.yaml
This reverts commit 736e4ecf43025c2866312e7b5fa0ca5d43a05997.
/assign @mpherman2
> Revert "Add '-temp' suffix to in-repo config presubmits to avoid conflict."

- .prow/presubmits.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
> Make OSS Prow config validation check for unknown fields in job config.

- prow/oss/cluster/crier-ghapp.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/hook-ghapp.yaml
- prow/oss/cluster/hook.yaml
The app was confirmed to be installed in the repo
> grpc-ecosystem uses GitHub app for prow

- prow/oss/cluster/crier-ghapp.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/hook-ghapp.yaml
- prow/oss/cluster/hook.yaml
The app was confirmed to be intalled in the org
> Googleforgames org uses GitHub app

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
For both oss and knative prows
> Prow auto-deploy cron adjusts against daylight saving

- prow/oss/cluster/sub.yaml
This reverts commit f7d1d7b671bd2bbc831762f953a856f4b321e0c7.
> Revert "Migrate sub to use GitHub app"

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
Just confirmed that it has cleaned up everything, should be safe to remove
> Delete hmac reconciler job

- prow/oss/plugins.yaml
> Replace stick lgtm team.

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
we migrated these to concourse pipeline
> gcp-guest: remove obsolete postsubmits

- prow/oss/cluster/sub.yaml
This reverts commit ec3c9a3156e0af5f0723233aff50c732d58da5a4.
Saw errors in caching, likely a bug
> Revert "Revert "Revert "Migrate sub to use GitHub app"""

- prow/knative/knative-autobump-config.yaml
It's proved to work as kubernetes/test-infra#24414
> Knative-prow autobump PR not assigned to anyone

- prow/oss/terraform/modules/alerts/main.tf
> Add an alert for KES errors.

- prow/oss/cluster/monitoring/prow_podmonitors.yaml
- prow/oss/cluster/sub.yaml
/cc @cjwagner @listx @mpherman2
> Podmonitor also monitors sub

- go.mod
- go.sum
There was a vulnerability fixed in upstream, bring it in here as well
/cc @cjwagner @mpherman2 @listx 
cc @fejta
> Update go.mod to use latest test-infra 20211209213704-46d865fbe139

- prow/oss/plugins.yaml
>
> This is already feasible from prow side, just need to update config_updater glob to respect yml
/cc @cjwagner
> Prow jobs defined in .yml files are also respected

- prow/oss/terraform/modules/alerts/main.tf
/assign @chases2 @chaodaiG 
This has already been deployed.
> Add alerts for tide sync and status controller heartbeats.

- prow/oss/config.yaml
This reverts commit 1243ba3c945840624d4c3b832c706807d6e81abc.
/hold
I will remove the hold tomorrow.
> Revert "add banner for Prow User Survey (2021 year-end)"

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Depends on https://github.com/kubeflow/pipelines/pull/7115 being merged first.
Part of https://github.com/kubeflow/pipelines/issues/6377
> test(kubeflow): kfp integration test v2

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Part of https://github.com/kubeflow/pipelines/issues/6377
> test(kubeflow): remove kubeflow-pipeline-sample-test and kubeflow-pipeline-component-test

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
So we can catch issues like this earlier https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/7137/kubeflow-pipeline-e2e-test/1478865285912989696
cc @chensun @Bobgy
> pipelines: enable e2e test for frontend changes

- prow/knative/plugins.yaml
Make use of the feature added here kubernetes/test-infra/issues/21581
> Enable github workflows retest in knative repos

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Pending https://github.com/kubeflow/pipelines/pull/7173
> test(pipelines): Update test config to accommodate code move for v2.

- prow/knative/cluster/500-kubernetes-external-secrets_crd.yaml
- prow/knative/cluster/500-kubernetes-external-secrets_deployment.yaml
- prow/knative/cluster/build/500-kubernetes-external-secrets_crd.yaml
- prow/knative/cluster/build/500-kubernetes-external-secrets_deployment.yaml
- prow/oss/cluster/kubernetes-external-secrets_crd.yaml
- prow/oss/cluster/kubernetes-external-secrets_deployment.yaml
Necessary to upgrade K8s clusters to 1.22+
> Update KES deployments and CRDs for K8s 1.22+.

- prow/knative/cluster/500-kubernetes-external-secrets_rbac.yaml
- prow/oss/cluster/kubernetes-external-secrets_rbac.yaml
these are copy/pasted from https://github.com/external-secrets/kubernetes-external-secrets/tree/8.5.1
/cc @cjwagner
> Add missing RBAC for KES

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Revert the run condition part of the change from https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1419
/assign @zijianjoy
> test(pipelines): restore v2 presubmit tests to always run

- .prow/presubmits.yaml
- prow/knative/plugins.yaml
> Knative Prow jobs path was updated to prow/jobs, updating config_updater plugin config

- .prow/presubmits.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/deck_private_deployment.yaml
- prow/oss/cluster/gerrit.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/horologium.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
- prow/oss/cluster/sub.yaml
- prow/oss/cluster/tide.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
- prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml
Also bump prow version, as autobump is blocked by inrepoconfig(which is nice)
/cc @chases2  @mpherman2
> Update prow jobs entrypoints with images produced by ko

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
* prune credentials presets
* prune extra_refs
> gcp-guest: prune creds, extra_refs

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
* copy from compute-image-tools/test-infra/prow/config.yaml
* remove volume mounts and service account key references
* add cluster parameter
> gcp-guest: add legacy periodics

- prow/knative/config.yaml
Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
> Separate knative prow reruns by org

- prow/knative/config.yaml
I did it in https://github.com/knative/test-infra/pull/3129, but forgot to move the change to oss-test-infra.
/cc @michelle192837
> Update Prow job age and max pod age for Knative Prow

- prow/oss/plugins.yaml
Need to use the name, not the slug
> Correct sticky team name.

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Signed-off-by: Wayne Zhang <qiwzhang@google.com>
> ESPv2: update build image

- prow/oss/cluster/cluster.yaml
> Fix 'grow' 'gprow' typo in ingress definition.

- README.md
- prow/oss/README.md
- prow/oss/cluster/monitoring/additional-scrape-configs_secret.yaml
- prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
- prow/oss/config.yaml
- prow/oss/onboarding.md
- prow/oss/terraform/main.tf
- prow/tests/README.md
> Update links to OSS-Prow to use the new domain.

- prow/oss/terraform/main.tf
> alerts: add comment

- prow/oss/config.yaml
- prow/oss/plugins.yaml
Fixes https://github.com/GoogleCloudPlatform/netd/issues/128.
> Adding GoogleCloudPlatform/netd (moving from Kubernetes's Prow)

- ml/tf-prow-squad.ipynb
A jupyter notebook that demonstrates how to a Vertex AI and tensorflow
to fine tune a BERT model to solve the SQuAD v1.1 dataset, aka highlight
the right answer in a paragraph.
(Click burger -> [view file](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/6270e6a573c3486060176432926e8fa01dcdc00a/ml/tf-prow-squad.ipynb) to see the contents)
> Fine-tune BERT for squad.

- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
The job depends on the config file from the repo. Also btw change the trigger of the postsubmit job to not trigger with job change
/cc @cjwagner @chases2
> Fix gencred periodic job by cloning this repo

- prow/oss/Makefile
- prow/oss/run-k8s-binary.sh
This will help the case where gencred refresher failed more than 2 days.
/cc @cjwagner @listx @mpherman2
> Break glass target for gencred refresher

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Changes from https://github.com/GoogleCloudPlatform/esp-v2/pull/699
> Update espv2 image with latest tooling

- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/deck_private_deployment.yaml
so that we won't get surprised
> Pin oauth2 image version to v7.2.1

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
- Update kubekins to match k8s version
- Reduce number of IPs allocated on network per cluster
Signed-off-by: nareddyt <tejunareddy@gmail.com>
> Update ESPv2 e2e images

- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
It will be enabled as inrepoconfig in testgrid repo
> Remove pull-testgrid-all job

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
presubmit has gotten out of sync with build targets
> update build targets for guest agent

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> correct typo

- prow/oss/config.yaml
- prow/oss/plugins.yaml
Add different prow plugins to make PR reviews similar to other GCP projects.
> Update prow plugins for compute-image-import.

- prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
This reverts commit 7071c300d658368cf08735268b524a889adb024d.
> Revert "experimental bump kind to 0.14.0"

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Changes to docker image: https://github.com/GoogleCloudPlatform/esp-v2/pull/729
Signed-off-by: nareddyt <tejunareddy@gmail.com>
> Update ESPv2 jobs to use python3

- prow/oss/config.yaml
We should revert this after the deadline passes.
/cc @chaodaiG @cjwagner
> add banner for Prow User Survey (2022 mid-year)

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Adds a KFP SDK execution test suite to replace `kubeflow-pipelines-samples-v2`.
> add KFP SDK execution test suite

- .prow/presubmits.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/gerrit.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/horologium.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
- prow/oss/cluster/sub.yaml
- prow/oss/cluster/tide.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
This reverts commit c5253fac60e1f2a7646460008f7942660b655460.
/assign @cjwagner @chaodaiG
> Revert "Bumping oss-prow"

- prow/oss/config.yaml
Reminder email will be sent out tomorrow
Context: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1738
/cc @cjwagner
> Update survey banner to reflect new deadline

- prow/oss/config.yaml
> revert survey banner

- prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
Update the Prow job image to a more recently built image that has `clang-13` installed.
> Update google/jwt_verify_lib CI image

- prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
Image is created from https://github.com/google/jwt_verify_lib/pull/89.
> Update jwt_verify_lib CI image

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Also update kubekins image to latest stable GKE version
> Update ESPv2 image deploy type to default COS_CONTAINERD

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
> Add quotation

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
/hold and merge after https://github.com/kubeflow/pipelines/pull/8907
> make KFP SDK Python 3.11 tests required and visible

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
Please submit this change after the previous PR was submitted and postsubmit job succeeded. Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.
> Add build cluster kubeconfig for gcsfuse

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
Dockerfile changes in https://github.com/GoogleCloudPlatform/esp-v2/pull/831
> Update gcpproxy-prow image to latest build with go1.20.5

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Add yaml config for windows sbom presubmit, following the format of the enterprise linux presubmit
> Enable windows sbom presubmit

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Replace the powershell variable with the secret command
> Use secret for powershell variable instead of hard coded value

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
The path to shell requires the / to be accessed
> Use the absolute path to shell

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
> Use shell command on new docker image

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
Set the secret variable before running daisy, all in one bash command
> Run bash and daisy in one command

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/kubernetes_external_secrets.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
Reverting changes introduced in PR 1231 and 1232.
More context: (internal):
https://yaqs.corp.google.com/eng/q/144582480517660672
> Unregister bms-oracle-team BYO build cluster

- prow/oss/cluster/kubernetes_external_secrets.yaml
- prow/oss/gencred-config/gencred-config.yaml
More details (internal references) on this:
* YAQS:  https://yaqs.corp.google.com/eng/q/144582480517660672?ved=0CAAQ0qAKahcKEwiY97rp_YSBAxUAAAAAHQAAAAAQHA
* TDD: [go/bmx-ci:pr-triggered-test-automation](http://go/bmx-ci:pr-triggered-test-automation)
* The full run of `create-build-cluster.sh` is at https://b.corp.google.com/issues/290186907#comment17
> Add external secret from build cluster for bms-oracle-team

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
Please submit this change after the previous PR was submitted and postsubmit job succeeded. Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.
> Add build cluster kubeconfig for bms-oracle-team

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Add periodics for cit performance tests at a 12 hour interval
> Cit 12 hour performance periodics

- prow/oss/config.yaml
- prow/oss/plugins.yaml
- prow/prowjobs/GoogleCloudPlatform/k8s-config-connector/OWNERS
Setting up the minimal config & structure.
> Onboard GoogleCloudPlatform/k8s-config-connector

- .prow/presubmits.yaml
- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/gerrit.yaml
- prow/oss/cluster/ghproxy.yaml
- prow/oss/cluster/grandmatriarch_default.yaml
- prow/oss/cluster/grandmatriarch_test-pods.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/horologium.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
- prow/oss/cluster/sub.yaml
- prow/oss/cluster/tide.yaml
- prow/oss/config.yaml
- prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
- prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
- prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
> Bump OSS-Prow to test out git v2 switch.

- prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
The docker container will use non root USER to run cmd
> Update cloudesf prowjob image to Oct 12

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
> Update gcp-guest owners.

- README.md
update the link for configuring prow jobs, add some additional context to the resources.
> fix: update broken link

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
[Python 3.12.0](https://www.python.org/downloads/release/python-3120/) was released on October 2, 2023.
> add KFP SDK Python 3.12 presubmits

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Runs `kfp` tests when `kfp-pipeline-spec` changes.
Runs `kfp-kubernetes` tests when `kfp` or `kfp-pipeline-spec` changes.
> run `kfp` tests on `kfp-pipeline-spec` changes

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
> Add oslogin-cit to cleanerupper runs

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Latest runs are timing out with the windows images
/cc @zmarano @koln67
> Switch cit-periodics 4h => 5h

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
make a noop change to kick our prow cluster into picking up config changes in #2176
/assign @zmarano
> kick prow cluster

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Run storage/networkperf and shapevalidation once per day on ubuntu devel images

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Run ubuntu daily cit in compute-image-test-pool projects

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Split ubuntu daily cit dashboard into performance and shapevalidation

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Alert when there have been no results in 24hours
Provide a link to a runbook (to be written)
/cc @elicriffield @zmarano
> Bump cit-periodics broken-column-threshold to 1.5%

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
go.mod changes in compute-daisy require us to run gobuild and gocheck on each directory with a module in it
/cc @bkatyl @zmarano 
GoogleCloudPlatform/compute-daisy#43
> Update compute-daisy presubmit config

- prow/oss/config.yaml
Moving to managing PRs with copybara
/assign @bkatyl
> Disable tide on compute-daisy

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml
> Run all daisy status checks for every PR

- prow/oss/plugins.yaml
Configured only for GoogleCloudPlatform/compute-daisy
/cc
> Trust copybara service to trigger tests

- .prow/OWNERS
- OWNERS
I will be changing my $DAYJOB and won't be working on this project directly any more.
> remove listx from OWNERS

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
Delete the presubmit test that are related to python3.7. Bump the version for some of the tests
/cc @chensun @connor-mccarthy
> Modify the test related to python3.7

- prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
This commit brings changes from #2228 and #2233 to the release branch.
> Change the default Git provider to CSR

- prow/oss/config.yaml
Reference: https://docs.prow.k8s.io/docs/components/optional/branchprotector/
https://github.com/kubeflow/community/issues/661
> chore(kubeflow): Remove Google CLA check for kubeflow.

- prow/oss/plugins.yaml
Merging changes will be managed by copybara, prowjobs will be used for presubmits.
/cc @michelle192837 @cjwagner
> Onboard github.com/GoogleCloudPlatform/cloud-image-tests to prow

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/cloud-image-tests.yaml
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Add presubmit tests to cloud-image-tests
Remove imagetest presubmits from guest-test-infra
/cc @bkatyl @zmarano
> Update cloud image test presubmits

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
/assign @dowgird
/cc @dowgird
/cc @bkatyl
/cc @koln67
> Add new test grid for osconfig-agent pkg testing version

- prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml
The referenced test script no longer exists
> chore: remove kubeflow-pipelines-components-google-cloud-python38

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
> Clean load balancers in guest os projects

- prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
> Bump the Config Sync release branch to v1.19

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/galog.yaml
/cc @dorileo @ChaitanyaKulkarni28
> Add galog presubmit checks

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
See https://cloud.google.com/compute/docs/images/os-details for more details.
> Remove deb11-arm64 as it deprecated

- prow/oss/plugins.yaml
/cc @dorileo @ChaitanyaKulkarni28
> Onboard GoogleCloudPlatform/galog to prow

- prow/oss/cluster/cherrypicker.yaml
- prow/oss/plugins.yaml
I think I've got all the correct secrets and configuration to wire this up correctly, but if I've missed something we can iterate.
Fixes https://github.com/GoogleCloudPlatform/oss-test-infra/issues/2343
/hold
/assign @nathanperkins @michelle192837 
/cc @andreyvelich
> Setup cherrypicker external-plugin for Kubeflow org.

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
* Drop trailing comma in cit-periodics-rhel
* Double parallel_count for cit-periodics-windows to address timeouts
/cc @bkatyl @koln67
> Address issues with cit-periodics

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/galog.yaml
- prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml
/cc @dorileo @ChaitanyaKulkarni28 @a-crate
> Trigger presubmits for galog and google-guest-agent on any file change, not just go files

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Moving to internal testing framework
> Removing performance tests

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Add cit-periodics-accelerator-images config

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Use guestos A3Ultra reservations for accelerator image prow runs

- prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
> Update Config Sync release branch CI to v1.20

- prow/oss/config.yaml
- prow/oss/plugins.yaml
> Switch guest-configs to manage PRs with copybara instead of tide

- prow/oss/cluster/kubernetes_external_secrets.yaml
- prow/oss/gencred-config/gencred-config.yaml
CL Auto generated by create-build-cluster.sh.
> Add external secret from build cluster for openshift-eng

- prow/oss/cluster/crier.yaml
- prow/oss/cluster/deck.yaml
- prow/oss/cluster/deck_blueprints_deployment.yaml
- prow/oss/cluster/hook.yaml
- prow/oss/cluster/prow-controller-manager.yaml
- prow/oss/cluster/sinker.yaml
Please submit this change after the previous PR was submitted and postsubmit job succeeded. Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.
> Add build cluster kubeconfig for openshift-eng

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
Pass in the accelerator type param which was added to cloud image tests.
> Pass in the accelerator type

- prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Update the presubmit job configuration to run in the new "build-gcp-oracle-team" build cluster
> Migrate presubmit jobs to the new "build-gcp-oracle-team" build cluster

- prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Set up a linter for Ansible files to enforce consistent formatting and catch syntax errors early
> Setting up a linter for Ansible files 

- prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml
Update ConfigMaps to reference new JSON configs for Oracle RAC
Tracking internally in b/324127807
> Switch from single-instance configuration to RAC cluster

- prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
> Update Config Sync release branch CI to v1.21

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
> Update reservation in a4 prow grid

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/OWNERS
> Update OWNERS file

- prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml
/cc @dorileo @ChaitanyaKulkarni28 
It doesn't support days, just hours.
> Fix time flag for guest-package-builder cleanerupper

- prow/oss/plugins.yaml
I updated milestone for Kubeflow SDK v0.2
/cc @kramaranya @szaher @astefanutti @Electronic-Waste
/assign @airbornepony @chases2 @cjwagner @michelle192837 @nathanperkins
> feat: Add v0.2 milestone for Kubeflow SDK
