GoogleCloudPlatform/oss-test-infra

prow/cluster.yaml
prow/config.yaml

To pick up https://github.com/kubernetes/test-infra/pull/12406 for kunit gerrit cannot trigger tests
Also see if tide would work.
/cc @cjwagner

bump oss-prow to v20190430-6a7dd776a

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Move to the gobuild-liam image, which doesn't have hardcoded build targets but takes targets as input.

Use liam's gobuild container image

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

```
{"component":"plank","error":"invalid presubmit job osconfig-presubmit-gocheck: decorated job containers must specify command and/or args","jobConfig":"/etc/job-config","level":"error","msg":"Error loading config.","prowConfig":"/etc/config/config.yaml","time":"2019-05-03T00:58:45Z"}
```
/assign @hopkiw

add explicit command/args to gcp-guest jobs

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

`decorate:true` does seem to do the work our wrapper does, so testing with some non-wrapper versions of these images.

GCP-guest: use non-wrapper versions when decorated

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

The container image currently is just a hello world shell script. Once the postsubmit job is tested, there will be a separate PR for the build and signing job

Add test post submit job to be triggered on osconfig repo

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

We aren't using this secret from old cluster in these jobs, can be re-added later if necessary.

Update gcp-guest containers

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

ran with https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/32/pull-prow-config-validate/1125863189448232960 which looks ok, also tried docker run. (checkconfig doesn't provide any output upon success though..)

use checkconfig image for presubmit

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

the daisy builder image doesn't explicitly set the GOOGLE_APPLICATION_CREDENTIALS variable because it was hardcoded to a path that's only known by prow. instead, it will use whatever credentials are configured by default, and for prow we set the variable as an override of the default.

rename daisy-builder; add env

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

`debian` doesn't have the necessary build tools and this is a make based repo, don't want to clutter it with shell scripts specific to prow or have a super customized container image for this either. compromised on debian+build-essential as an available image.

Update image for cpp builds

---

prow/cluster.yaml

Addresses issue #66 
Reconfigures gerrit to use the service-account on the cluster to keep state using a cloud file instead of a persistent volume
/assign @krzyzacy @fejta

Move Gerrit to Cloud Sync

---

prow/Makefile

It is *annoying* and *unsafe* to **change** the Kube `current-context` in the user's environment; instead, we should change it **only** for the execution of the make targets. 
Due to how `gcloud ... get-credentials` works, we can achieve this by exporting a temp `KUBECONFIG` where `gcloud` will set the cluster and user in this file for the life of the subprocess.

Preserve environment Kube context after "get-cluster-credentials"

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

these filters made sense when this was in the shared compute-image-packages repo, now we should pretty much always guarantee builds and tests pass.

always run oslogin tests

---

prow/Makefile
prow/Makefile.gcloud.mk
prow/grandmatriarch_default.yaml
prow/grandmatriarch_test-pods.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Summary of changes:
1. Pulled in the `Makefile.gcloud.mk` file, used internally and in Istio  which contains a bunch of helpers.
2. Separated out `grandmatriarch` *default* and *test-pods* deployments into separate files.
3. Added `deploy-build` command to `Makefile` for deploying build cluster.
4. Enabled `build` cluster on test-infra presubmits.
/assign @cjwagner @fejta

Setup a general build cluster for oss-prow

---

prow/cluster/cluster.yaml

> This will address the rbac issues regarding plank : #106
Same change reported: kubernetes/test-infra#14489 and  kubernetes/test-infra#14491.
/assign @krzyzacy @fejta

Add missing rbac verbs for plank prowjobs resource

---

prow/bump.sh

this wasn't working, corrected to what appear to be the matching paths.

correct bump.sh paths

---

prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml

Automatically pushes images when a change is made to a testgrid command
Hold for secrets to be added
/hold

Testgrid: Add Automatic Image Deployment

---

prow/plugins.yaml

* Move plugins that respond to a command to org level
* Enable label plugin at org level
Fixes https://github.com/GoogleCloudPlatform/oss-test-infra/issues/104 
/assign @chases2 @BenTheElder @cjwagner

Enable override plugin in oss-test-infra

---

prow/plugins.yaml

/assign @cjwagner @chases2 
```yaml
{
insertId: "5tvffffjgwl78"  
jsonPayload: {
component: "hook"   
error: "[plugins [golint] are duplicated for GoogleCloudPlatform/testgrid and GoogleCloudPlatform]"   
file: "prow/plugins/plugins.go:276"   
func: "k8s.io/test-infra/prow/plugins.(*ConfigAgent).Start.func1"   
level: "error"   
msg: "Error loading plugin config."   
path: "/etc/plugins/plugins.yaml"   
}
labels: {…}  
logName: "projects/oss-prow/logs/hook"  
receiveTimestamp: "2019-10-10T23:53:30.809873253Z"  
resource: {…}  
severity: "ERROR"  
timestamp: "2019-10-10T23:53:26Z"  
}
```

Fix plugin config

---

prow/cluster/cluster.yaml
prow/config.yaml

Enable `deck` rerun for [Googlers](https://github.com/orgs/GoogleCloudPlatform/teams/googlers).
closes #68
> `github-oauth-config` and `cookie` secrets loaded to cluster.
/assign @cjwagner @krzyzacy

Enable OSS rerun for all googlers

---

prow/cluster/cluster.yaml
prow/cluster/grandmatriarch_default.yaml
prow/cluster/grandmatriarch_test-pods.yaml
prow/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This bump broke gerrit.
This reverts commit 84bb7fa486fa7c79965dadd93d9a320eaa273ab5, reversing
changes made to 2de39cd82895e9d2ed17735de4a9bce998f210ff.

Revert "Merge pull request #143 from google-oss-robot/autobump"

---

prow/cluster/cluster.yaml

The current configuration is deprecated and should break this week. Fixes #146.

Set --cookie-secret for deck

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

We add the `extra_refs` block to packagebuild so it always gets the new packagebuild scripts. This is temporary way to use existing daisy-builder container until we make a fully-complete packagebuilder container.
Also update annotations to match testgrid config

add extra_refs and annotations to packagebuild

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
testgrid/config.yaml

This should enable Prow annotations, and allow TestGrid to automatically update k8s/test-infra as other sources are.
/assign @fejta @michelle192837 
/cc @hopkiw

Add Prow Job to push TestGrid Configs to k8s-testgrid

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
testgrid/config.yaml

Additions will be necessary to remove conflicts and add tests so that configuration will pass in correctly.

Addition of TestGrid dashboards

---

prow/prowjobs/GoogleCloudPlatform/api-proxy/api-proxy.yaml

They are two basic jobs which no external files or network required.

apiproxy: add build and presubmit jobs to prow

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

without this this wf files are not available for builds
sample failure
https://storage.googleapis.com/oss-prow/logs/osconfig-build/1195399548411842560/build-log.txt

Import guest build tools for post-submit jobs

---

prow/cluster/cluster.yaml

/assign @Katharine @chases2 
```console
test-infra$ experiment/workload-identity/enable-workload-identity.sh oss-prow us-west1-a prow
++ gcloud beta container clusters describe prow '--format=value(workloadIdentityConfig.identityNamespace)' --project=oss-prow --zone=us-west1-a
++ gcloud beta container node-pools list --cluster=prow '--format=value(name,config.workloadMetadataConfig.nodeMetadata)' --project=oss-prow --zone=us-west1-a
Nothing to do
```
After merging I can run:
```console
test-infra$ experiment/workload-identity/bind-service-accounts.sh oss-prow us-west1-a prow default gerrit oss-prow@oss-prow.iam.gserviceaccount.com
Service account has wrong/missing annotation, please declare the following to …
```

Bind the gerrit service account to a GCP one

---

prow/cluster/cluster.yaml

Use workload-identity to authenticate instead of a secret

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This should be compatible with 1.14 clusters
ref https://github.com/kubernetes/test-infra/issues/15842

Update gcloud-in-go to latest image.

---

prow/config.yaml
prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
prow/serviceaccounts/GoogleCloudPlatform_testgrid_serviceaccounts.yaml

Also get rid of presets (only used in one location)
Need https://github.com/GoogleCloudPlatform/testgrid/pull/82 to merge first

Push testgrid images using workload identity

---

prow/cluster/grandmatriarch_default.yaml
prow/cluster/grandmatriarch_test-pods.yaml

ref #202 
This will allow me to bind the service accounts together and send a PR to switch it over to using workload-identity

Annotate grandmatriarch service-account

---

prow/cluster/grandmatriarch_default.yaml
prow/cluster/grandmatriarch_test-pods.yaml

ref #202 
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/224#issuecomment-573816169 validates that all three service accounts can access the GCP service account

Use workload-identity for grandmatriarch

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
prow/serviceaccounts/build/GoogleCloudPlatform_esp-v2_serviceaccounts.yaml

ref #202 #222 
Merging this will create the k8s SA, which will allow me to bind it to the gcp SA and then update the job to remove the secret (and then delete the secret)

Use serviceAccount for bookstore-managed job

---

prow/cluster/cluster.yaml

Reverts GoogleCloudPlatform/oss-test-infra#240
see internal discussion :man_facepalming:

Revert "switch tide to clusterrole so it can create pods in other namepsaces"

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

The old image has error to pull k8s-release
Err msg:
error during gsutil cat gs://kubernetes-release-dev/ci/latest-1.13.txt: exit status 1

update to latest e2e image

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
prow/serviceaccounts/build/GoogleCloudPlatform_esp-v2_serviceaccounts.yaml

ref #202 #222 
An owner of `github-prow-jobs@cloudesf-testing.iam.gserviceaccount.com` will need to run the following first:
```
gcloud iam service-accounts add-iam-policy-binding \
"--project=cloudesf-testing" \
--role=roles/iam.workloadIdentityUser \
"--member=serviceAccount:oss-prow.svc.id.goog[test-pods/gcp-esp-v2-default]" \
github-prow-jobs@cloudesf-testing.iam.gserviceaccount.com
```
/assign @TAOXUY @hopkiw

Use workload identity for esp-v2 jobs

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

This reverts commit 7621fe2b5c698f92aa7aa34e282a57ecb965af5e.
Eric was trying to migrate mounting service account file to workload identity but it is still unfinished. Revert his change until he comes back.

Revert "Use workload identity for esp-v2 jobs"

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
testgrid/config.yaml

Also makes changes to ensure that this presubmit passes:
- Dashboard 'googleoss-esp-v2' removed; no postsumits/periodics are run by that team

Mandate TestGrid Validation

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Fixes [failing job](https://prow.k8s.io/view/gcs/oss-prow/logs/push-testgrid-images/1227668576593252352) caused by Bazel bump
/assign @fejta
/assign @michelle192837

Bump bazelbuild image to 2.1.0

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

- Move those jobs using kubekins back to github-prow clusters
- Add one experimental job to test if our own cluster works

move e2e test using kubekins on github-prow temporarily

---

prow/Makefile
prow/serviceaccounts/build/GoogleCloudPlatform_esp-v2_serviceaccounts.yaml

The espv2 jobs no longer run in the shared cluster, so we no longer need this service account
/assign @TAOXUY

Delete gcp-esp-v2-default serviceaccount from shared cluster

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Previously, the espv2 cluster doesn't have the corresponding service account so e2e jobs failed. Now thoes SA are created so migrate e2e jobs.

Migrate espv2 e2e jobs from default cluster to espv2 cluster

---

prow/cluster/cluster.yaml
prow/config.yaml

Also tweaks things like pod timeout to match kubernetes/test-infra for
more useful debugging.
Lens will be enabled in follow-up PR if this works.

Enable reporting of pod info to GCS.

---

prow/create-build-cluster.sh

/assign @fejta 
The `./merge_kubeconfig_secret.py` command is a little off for this prow instance. I see two sets of config with keys `oss-config` and `oss-config-20200214`. The script will also change after https://github.com/kubernetes/test-infra/pull/16309 merges. I'm waiting to include that script until it has stabilized since it is needed by oncall and omitting it here won't block the cluster owner. I'll add it and correct the message then.

Add script to facilitate creating per-team build clusters.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

e2e script won't cleanup the subnet, which use up subnet quota and considering gob jobs work with `default gcp-network`, add back this flag.
This reverts commit 29365d8c10641d3d91567624fb1ceb86d2fa992c.

Revert "remove default network"

---

prow/cluster/cluster.yaml

The gflocks domain is retired, prepare to migrate to oss-prow.knative.dev
/assign @michelle192837 @clarketm

Disable http redirection.

---

prow/config.yaml

Use oss-prow.knative.dev for domain, enable testgrid integration
/assign @chases2 @michelle192837 
Sean transfigure syncs all these jobs to k8s-prow, right?

Fixup some URLs.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Like our gob-prow, move our e2e jobs in to us-west1-c so that they can be clean with `periodic-ESPv2-continuous-job-janitor`, which cleanup the e2e jobs in us-west1-c and older than 5hrs.

move continuous e2e jobs into us-west1-c

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

- Easier to filter jobs if they all have the same prefix
- Serverless janitor only cleans up resources at a day interval. Running it multiple times a day has no effect and may cause flakes (there is a race condition in the cleanup).

ESPv2: Rename periodic jobs and reduce serverless janitor interval

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

The long run jobs are often killed because of timeout and set it to be 5hrs like what we have in gob-prow.
https://oss-prow.knative.dev/view/gcs/oss-prow/logs/ESPv2-continuous-gke-e2e-tight-grpc-interop-managed/1232787558996381703

Add 5h timeout for continuous long run jobs

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Update the time out for cloud run long run jobs

Add 5h timeout for cloud run long run jobs

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

- Service account config matches all other jobs.
- Just let a single janitor clean up all locations, no need to duplicate it. We already have resources spilling into other zones.

Espv2 fix janitor

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

New image has [buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier)
Required for the coverage script in ESPv2

Update all prow images for ESPv2

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Prevents redundancy with k8s/test-infra, which is required for TestGrid utilities (ex. Transfigure) to function
Fixes #318

Rename ResultStore ProwJob

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

New image has JDK. This unblocks coverage reports: https://github.com/GoogleCloudPlatform/esp-v2/pull/56
Update only `coverage` jobs for now (safer).
Tested running coverage script inside this docker image.

Update coverage prow images for ESPv2

---

prow/cluster/cluster.yaml

I'm about 80% sure this certificate isn't being used, but would like some confirmation, if possible.

Removed deprecated ManagedCertificate

---

README.md
prow/README.md
prow/tests/README.md

Changes domain name in all documentation
Does not cover domain name in [prow/cluster/cluster.yaml](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/a9beebb04e4e85a178c994226a1408ef8680401c/prow/cluster/cluster.yaml#L306-L313); I'm not sure if that managed certificate is being used currently.

Domain is now oss-prow.knative.dev

---

prow/cluster/cluster.yaml

This is needed to allow aborting jobs for closed PRs and will resolve a few types of errors in the logs.
/assign @fejta

Fix hook RBAC and CRD validation.

---

prow/cluster/ghproxy.yaml

/assign @fejta 
I'm done boosting my GH activity stats. This time I checked that the deployment is valid with kind.

Fix ghproxy deployment selector.

---

prow/cluster/cluster.yaml
prow/cluster/ghproxy.yaml
prow/cluster/grandmatriarch_default.yaml
prow/cluster/grandmatriarch_test-pods.yaml
prow/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Reverts GoogleCloudPlatform/oss-test-infra#343
Currently preventing some jobs from starting at all.

Revert "Bump prow from v20200417-a6017ee5b to v20200422-8c8546d74"

---

prow/cluster/cluster.yaml

/assign @fejta, @BenTheElder, @cjwagner 
Triggering new Prow deployment with the old 0417 image (instead of the nonexistent 0422 image).

Touch cluster file to trigger Prow deployment.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
testgrid/config.yaml

- Cleanup long names and add basic descriptions
- Split presubmit vs periodic jobs into different dashboards, similar to Istio

[ESPv2] Better testgrid configuration

---

prow/cluster/cluster.yaml

As per flag warning: "missing required flag: please set to --github-token-path=/etc/github/oauth before June 2020"
/assign @fejta @chases2

Add required --github-token-path to hook/tide.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

These keep failing on `gcloud auth print-access-token`. I imagine it is a problem with GKE workload identity in the latest `gcloud`, as I cannot reproduce locally.
Reverting the image should be safe. E2E tests do not build envoy, so they don't need the latest changes.
Test failures: https://testgrid.k8s.io/googleoss-esp-v2-periodic#e2e-cloud-run-http-bookstore

[ESPv2] Revert back serverless e2e images

---

prow/config.yaml
prow/plugins.yaml
prow/prowjobs/google/exposure-notifications-server/OWNERS
prow/prowjobs/google/exposure-notifications-server/en-server.yaml

Webhooks for the repo are being sent to this Prow instance too now.
/assign @fejta @crwilcox @sethvargo

Enable trigger and add a job for en-server.

---

prow/config.yaml
prow/plugins.yaml

Depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/375
Hold for validation of dependent PR and synchronized merge with internal PR to disable automation on internal Prow.
/hold
/assign @crwilcox @sethvargo @fejta

Switch en-server from internal Prow to OSS Prow.

---

prow/plugins.yaml

There are a couple PRs in the `google/exposure-notifications-server` repo with failing statuses from the `pull-release-unit` job that was formerly run on the internal prow instance and has since been replaced with `pull-en-server-release-unit` on this Prow instance.  This PR enables the `override` plugin to allow repo admins to `/override pull-release-unit` to force the status to green and unblock the PR.
/assign @crwilcox @sethvargo

Allow en-server repo admins to override old job.

---

prow/cluster/cluster.yaml

Use blob-storage prefix instead of GCS
Set github-token-path explicitly.
ref https://github.com/GoogleCloudPlatform/oss-test-infra/issues/373

Update crier flags.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Due to quota issues (b/158767160), let's reduce it.
```
Your cron job will be run at: (5 times displayed)
2020-06-13 00:00:00 UTC
2020-06-13 12:00:00 UTC
2020-06-14 00:00:00 UTC
2020-06-14 12:00:00 UTC
2020-06-15 00:00:00 UTC
...
```

[ESPv2] Reduce periodic test triggering

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

/hold
Would be nice if we can manually test this job before pushing it
/assign @cjwagner @michelle192837

exposure-notification jobs use build cluster

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

The service account json key `gcs-access-service-account` was already mounted on build cluster, and GCS bucket `apollo-server-prow-test-bucket` was created as well. They are ready for a test now

Apollo Server test: add a canary job for testing GCS access token

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

The canary job for using service account auth GCS succeeded, move it to prod
Succeeded run: https://oss-prow.knative.dev/view/gcs/oss-prow/pr-logs/pull/google_exposure-notifications-server/497/pull-en-server-release-unit-canary/1275876003427651584
There are two commits for easier code review:
1. Delete canary job
1. Update prod job

Apollo server: move canary to prod

---

prow/knative/OWNERS
prow/tests/jobs_test.go

This is step 2 as described in #407 . Kubeconfig of knative prow cluster will be added onto oss-test-infra prow for managing knative prow core and plugin configs. Adding this guard to ensure knative prow cluster isn't accidentally used by any job to run workload
/assign cjwagner chizhg
/cc albertomilan

Protect knative prow cluster from being used by any job

---

prow/knative/plugins.yaml

This is a side effect of step 3 from https://github.com/GoogleCloudPlatform/oss-test-infra/pull/407
/cc chizhg cjwagner

Knative prow stop updating core and plugins. Mirror from https://github.com/knative/test-infra/pull/2255

---

prow/oss/plugins.yaml
prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

Seems updates were made to en-server. Trying to keep the two repositories test runner in sync.

mirror en-server config to en-verification-server

---

prow/oss/plugins.yaml

This is step 4 as described in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/407
Shouldn't merge until steps 1-3 are done
/hold

Updateconfig plugin updates knative prow configs from oss-test-infra prow

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml
testgrid/config.yaml

This job is set to run once per day initially
Success of this job is contingent on the creation of entrypoint script in exposure-notification-server repo. 
/cc @stati0n

Add performance test job for exposure notification server

---

prow/oss/cluster/cluster.yaml

Passing `kubeconfig`  as a parameter for hook deployment

Mount kubeconfig secret for hook

---

prow/knative/config.yaml

The previous attempt for testing updateconfig plugin failed due to hook deployment doesn't have kubeconfig mounted, which is fixed in #416. Create this PR for testing the 2nd time
/cc @chizhg 
/hold
Wait until #416 merged

Noop update on knative core config

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Basically copy/paste from auto bump job above. Other than job name and testgrid tab name, the only changes are env vars
/assign cjwagner

Add auto bump job for knative prow configs

---

prow/knative/config.yaml

**What this PR does, why we need it**:
This PR makes Spyglass highlight a handful of compile errors.
I created this after trying to diagnose why a [dependency update PR failed](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/google_knative-gcp/1371/pull-google-knative-gcp-build-tests/1278361112407969793). 
Spyglass showed:
```
---- Checking for forbidden licenses ----
-----------------------------------------
---- Wed Jul  1 09:31:42 PDT 2020
-----------------------------------------
2020/07/01 16:32:41 Getting artifacts dir from prow
Step failed: default_build_test_runner
============================
==== BUILD TESTS FAILED ====
============================
==== Wed Jul  1 09:32:41 PDT 2020
============================
Step failed: run_build_tests
+ EXIT_VALUE=1
+ set +o …
```

Spyglass highlights a handful of compile errors.

---

prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

This secret was taken form exposure-notifications-server, but is causing a build failure
https://oss-prow.knative.dev/view/gcs/oss-prow/pr-logs/pull/google_exposure-notifications-verification-server/85/pull-en-server-release-unit/1280340453987717120

Remove unused secret for EN verification server

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

Just noticed the repo had switched from `master` to `main`: https://github.com/google/exposure-notifications-server. Update the job so that it doesn't fail fetching `master`

Update baseref of exposure notification server from master to main

---

prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml

Supercedes https://github.com/GoogleCloudPlatform/oss-test-infra/pull/426
Image built from https://github.com/kubernetes/test-infra/pull/18204
To support https://github.com/GoogleCloudPlatform/testgrid/pull/141

Update testgrid bazel image to 2.1.0->3.0.0 variant

---

prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml

Fix typo introduced in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/427
I'm slightly confused because I copied the image name from https://storage.googleapis.com/kubernetes-jenkins/logs/post-test-infra-push-bazel/1280659794998333441/build-log.txt
So not sure how I should have known this ends up in the k8s-testimages repo instead

Fix typo in bazel image repo

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

The current job failed https://github.com/GoogleCloudPlatform/oss-test-infra/pull/432
```
{"component":"unset","error":"stat ${GOPATH}/src/github.com/knative/test-infra/config/prod/prow/jobs: no such file or directory","file":"prow/config/agent.go:314","func":"k8s.io/test-infra/prow/config.lastConfigModTime","jobConfig":"${GOPATH}/src/github.com/knative/test-infra/config/prod/prow/jobs","level":"error","msg":"Error loading job configs.","severity":"error","time":"2020-07-10T15:16:36Z"}
```
Use relative path should solve this problem.
Link for failed run: https://oss-prow.knative.dev/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/432/pull-knative-prow-config-validate/1281608234565636096
/cc @fejta @chizhg

Fix prow config validate job by using relative path

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Config check still failed, this time it's due to long job name. Updated the checkconfig job to also exclude long job name. Verified with checkconfig job in knative and there should be no more flag missing
Failed run: https://oss-prow.knative.dev/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/432/pull-knative-prow-config-validate/1281675679175282688
/cc @fejta @chizhg

Ignore long job name in knative prow config check

---

prow/knative/cluster/400-crier.yaml
prow/knative/cluster/400-deck.yaml
prow/knative/cluster/400-hook.yaml
prow/knative/cluster/400-horologium.yaml
prow/knative/cluster/400-ingress.yaml
prow/knative/cluster/400-plank.yaml
prow/knative/cluster/400-sinker.yaml
prow/knative/cluster/400-tide.yaml

Knative prow deployment definition has never had namespace defined. Not sure how `kubectl apply -f` magically figured out deploying prow components in default namespace. After migrating here they were deployed to test-pods namespace instead. 
Explicitly setting namespace to fix this problem
/cc @chizhg @BenTheElder

Knative prow deployment define namespaces

---

prow/knative/cluster/400-crier.yaml
prow/knative/config.yaml

1. Enable slack reporter for crier, based on the doc in https://github.com/kubernetes/test-infra/tree/master/prow/crier#slack-reporter. Please note I have created the `slack-token` on the Prow cluster, so it is now safe to update crier deployment.
2. Add `slack_reporter_configs` in the Prow core config file. Please note the job types to report is now empty, so this config will be a no-op and won't report any jobs. I will create followup PRs in knative/test-infra repo to enable this reporter for the specific jobs that we want.
/cc @chaodaiG

Enable slack reporter for crier

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

This service account is used for accessing mako
/assign @sethvargo

En: mount service account for performance test

---

prow/knative/config.yaml
prow/oss/config.yaml

> configuring the 'gcs/' storage provider suffix in the job url prefix is now deprecated, please configure the job url prefix without the suffix as it's now appended automatically. Handling of the old configuration will be removed in September 2020
/assign @chaodaiG @e-blackwelder

Remove legacy gcs/ suffix from job_url_prefix_config for both Knative and OSS Prow.

---

prow/knative/config.yaml

When this error happens, the log file is usually very large, so it would be helpful to highlight the error line in Spyglass.
/cc @chaodaiG

Add a regex in spyglass to highlight go build OOM error

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

Setting up this canary job for quickly figuring out what's required for running smoke test based on terraform deployment.
Note: this canary job will not be triggered automatically, so will not block PRs.

Add a canary e2e test job for en server

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

This reverts commit f810c97b. The release is done, we will setup a way to manually trigger these jobs in the future.
Prefer to revert this soon, as the periodic jobs keep overwriting the endpoints service, making it hard to test https://github.com/GoogleCloudPlatform/esp-v2/pull/287.

Revert "[ESPv2] Temporarily increase continuous test frequency"

---

prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Add hmac Prow postsubmit job for reconciling hmacs token secret when we use the config.yaml file to onboard new orgs/repos.
Note merging this PR will only add this Prow job, and the job will only be triggered in the next time config.yaml is updated.
/cc @cjwagner

Add hmac Prow postsubmit job

---

prow/knative/cluster/build/400-boskos-deployment.yaml
prow/knative/cluster/build/400-boskos-janitor.yaml
prow/knative/cluster/build/400-boskos-metrics.yaml
prow/knative/cluster/build/400-boskos-reaper.yaml

Reverts GoogleCloudPlatform/oss-test-infra#473
Knative Boskos is broken, too many projects are in cleaning state and there are a lot of Janitor error logs.
/cc @chaodaiG

Revert "Update knative boskos to use new image path, as well as update it to …"

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

This adds a presubmit for https://github.com/GoogleCloudPlatform/compute-image-tools.
[local-results.zip](https://github.com/GoogleCloudPlatform/oss-test-infra/files/5100408/local-results.zip) contains the output from running the job locally. Ideally I'd like to verify the results on `spyglass`; I tried setting up a local prow instance with [runlocal](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/runlocal), but that resulted in *many* build failures.
So: Any ideas on how to view this on a spyglass instance?
Testing:
* `bash pj-on-kind.sh boot-inspect-pytest`
* PR: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1326
Output structure:
```
tree /mnt/disks/prowjob-out/boot-inspect-pytest/1296276119707717632 …
```

Add prow job for disk-inspection-pytest.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Just `release/stable` should work:
https://github.com/kubernetes/test-infra/blob/fd124b768d9e95177125c6f3d19b3af8b5e71a03/kubetest/extract_k8s.go#L49
Fixes all the test failures currently due to GKE not supporting 1.14:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.14.10" found.
```

[ESPv2] Use any stable gke release, don't pin to 1.14

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

- `release/stable` using 1.18, which is not supported in GKE yet.
- `release/stable-1.16` would use 1.16.14, which is also not supported on GKE yet.
- So just provide a valid patch version that is supported.

[ESPv2] Pin to a specific release version

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

ESPv2's control plane library is depended by other projects and they will update the data plane first with lagged control plane, due to different release cadence. Try to add the api regression test to catch it.

Add api regression test

---

prow/knative/config.yaml

Exclude archived repos to get rid of the Tide warnings
/cc @cjwagner @chaodaiG

Exclude archived repos to get rid of the Tide warnings

---

prow/knative/cluster/300-crds.yaml

This is causing errors when hook tries to abort presubmits for PRs that are closed.

Allow Knative PJs to be aborted without completion time.

---

prow/oss/cluster/cluster.yaml

Which was removed in https://github.com/kubernetes/test-infra/commit/2408556a40ad1b0f117c41ac3f90a170aa842a4f

Removing deprecated `github-token-path` plank arg

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

This one is not updated in last [PR](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/500).

Update prow image for tsan

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml

Add a periodic job for terraform smoke test. This job cannot be ran at the same time with pull-en-server-release-e2e-canary, this will be fixed by using the project pool manager Boskos in following PR
/hold
Wait until https://github.com/google/exposure-notifications-server/pull/948

En server: terraform smoke test continuous job

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml
prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

The alerts will be sent to a google group, so far I'm the only one in the group
/cc @sethvargo @icco

En server: email notify if prow jobs failed

---

prow/oss/cluster/controller-manager.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/plank.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Manually created with the bump script since autobump is treating it as a no-op despite a merge conflict in the previous PR. (See https://github.com/GoogleCloudPlatform/oss-test-infra/pull/517)

Bump oss-prow from v20200921-becd8c9356 to v20200925-a1858f46d6

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

Two changes:
1. Don't run "go test" for e2e tests during presubmit.
2. Update directories to match new naming structure.
Ran pj-on-kind for  cli-tools-tests-presubmit-gocheck and cli-tools-tests-presubmit-gobuild
PR in compute-image-tools: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1379

compute-image-tools: Restructured tests directory.

---

prow/knative/cluster/200-cpu-limitrange.yaml
prow/knative/cluster/200-memory-limitrange.yaml

Knative serving compilation is CPU intensive, the e2e jobs transiently need to use up to 10 CPUs and get a great performance gain (from 7 minutes to 2 minutes). And the CPU spike only in the second half, which is  ~ 1 minute out of 30 - 50 minutes. So the chance of multiple jobs spiking the exactly the same time is not very high

Knative prow: default job cpu limit to 10

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1381 adds a new directory containing Go code called "common". This configures presubmits for that directory.
- Ran pj-on-kind for the three new presubmits

compute-image-tools: Presubmits for common directory

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This job had been silently failing, fix in https://github.com/kubernetes/test-infra/pull/19454
/cc @cjwagner @fejta

Fix oss prow autobump job path

---

prow/knative/cluster/303-prow-knative-dev_managedcertificate.yaml

Update Knative Prow to use Google-managed SSL certificates, similar as all other Prow instances we manage. This will prevent the SSL certificates to be expired since Google Cloud can renew it automatically.
I have switched Knative Prow to use the new certificate and it's working well without downtime.
/cc @chaodaiG @coryrc 
FYI @peterfeifanchen @albertomilan

Update Knative Prow to use Google-managed SSL certificates

---

prow/knative/cluster/301-rbac.yaml
prow/knative/cluster/400-crier.yaml

Following https://github.com/kubernetes/test-infra/tree/master/workload-identity to use workload identity for Prow control plane deployments. The changes have been applied on the Knative Prow cluster and everything is still working fine.

Use workload identity for Prow control plane deployments

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Some tests keep failing due to resources shortages in GCE. `e2` instances optimize against this error scenario.

[ESPv2] Update machine type for GKE jobs to `e2-standard-2`

---

prow/knative/config.yaml

Nested folders are a valid use case which other tools are prepared for and Spyglass was omitting internal inspection. This was causing inconsistent behaviors and creating mismatching signals on researches

Expand regexp for junit files in Spyglass

---

prow/knative/cluster/301-rbac.yaml
prow/oss/cluster/crier.yaml

This should resolve errors like the following:
```yaml
{
component: "crier"   
error: "failed to report job: failed to add finalizer to pod: failed to patch pod: pods "b7351861-0caf-11eb-9b02-0242ac110002" is forbidden: User "system:serviceaccount:default:crier" cannot patch resource "pods" in API group "" in the namespace "test-pods""   
file: "prow/crier/controller.go:149"   
func: "k8s.io/test-infra/prow/crier.(*reconciler).Reconcile"   
key: "default/b7351861-0caf-11eb-9b02-0242ac110002"   
level: "error"   
msg: "Reconciliation failed"   
prowjob: "b7351861-0caf-11eb-9b02-0242ac110002"   
reporter: "gcsk8sreporter"   
}
```
/assign @fejta @e-blackwelder @chases2

Update crier RBAC to support pod finalizers.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Clang-10 is needed to build with the latest envoy. Tested with this image locally.
Dockerfile changes are located in https://github.com/GoogleCloudPlatform/esp-v2/pull/375.

[ESPv2] Update to prow images with clang-10

---

prow/knative/cluster/301-rbac.yaml

I missed deck when I switched Knative Prow to use workload identity in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/535
Fixes https://github.com/GoogleCloudPlatform/oss-test-infra/issues/539
/cc @cjwagner

Allow deck k8s SA act as prow-control-plane Google SA

---

prow/oss/cluster/deck.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/tide.yaml

Servicemonitor label selectors ([e.g.](https://github.com/kubernetes/test-infra/blob/e1964383f206385c7ed6f3c16c5f5c778833b57c/config/prow/cluster/monitoring/prow_servicemonitors.yaml#L19-L21)) match against the service's labels, not the labels of the pods that back the service. The `deck`, `hook`, and `tide` services were missing labels so their servicemonitors failed to match any services to scrape. The new services that were added in this pr https://github.com/GoogleCloudPlatform/oss-test-infra/pull/548 already specify labels and are working as expected.
/assign @chaodaiG @fejta

Add missing "app" labels to Prow services.

---

prow/knative/cluster/400-ghproxy.yaml
prow/oss/cluster/ghproxy.yaml

```
The deprecated `--legacy-disable-disk-cache-partitions-by-auth-header` flags value is `true`. If you are a bigger Prow setup, you should copy your existing cache directory to the directory mentioned in the `Not using a partitioned cache because legacyDisablePartitioningByAuthHeader is true` messages to warm up the partitioned-by-auth-header cache, then set the flag to false. If you are a smaller Prow setup or just started using ghproxy you can just unconditionally set it to `false`.
```
This change will effectively reset the ghproxy caches for both of these instances which will temporarily increase GitHub API ratelimit consumption. This should be safe for the small OSS prow instance and I suspect it won't be an issue for the Knative Prow instance either, but we should merge this …

Enable ghproxy cache partitioning.

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml
prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

There are 3 jobs so far, separating them by 30 minutes apart can avoid them running at the same time, which could help with a GCS concurrent read/write conflict

EN: prow jobs running 30 minutes apart

---

prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml

Prow tests should execute in the build cluster: secretmanager-csi-build

Add cluster to secrets-store-csi-driver-provider-gcp

---

prow/oss/cluster/monitoring/mixins/Makefile

Makefile target can only be referenced as dependency
/cc @cjwagner

Fix Makefile for monitoring

---

prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

It's been updated in https://github.com/google/exposure-notifications-verification-server/pull/841
/assign @p3y1c2n

EN jobs: fix verification server e2e test job entrypoint

---

prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

It's changed from e2e-tests.sh to ci-e2e-tests.sh in https://github.com/google/exposure-notifications-verification-server/pull/884

EN: update verification server jobs scripts path

---

prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml

We had to migrate our GCP project containing our container registry for
our Prow Docker image recently, so update the corresponding container
registry location in Prow.

Update container registry for KUnit GoB instance

---

prow/knative/cluster/301-rbac.yaml

Alertmanager warned sinker not deleting pods, this should fix it
/assign @fejta

Add missing sinker RBAC on knative prow

---

prow/knative/cluster/400-plank.yaml
prow/knative/cluster/400-prow-controller-manager.yaml
prow/oss/cluster/plank.yaml
prow/oss/cluster/prow-controller-manager.yaml

This component is replaces (embeds really) plank
https://github.com/kubernetes/test-infra/blob/master/prow/ANNOUNCEMENTS.md#breaking-changes

Prepare to switch oss/knative to prow-controller-manager

---

prow/knative/cluster/400-crier.yaml
prow/knative/cluster/400-deck.yaml
prow/knative/cluster/400-ghproxy.yaml
prow/knative/cluster/400-hook.yaml
prow/knative/cluster/400-horologium.yaml
prow/knative/cluster/400-prow-controller-manager.yaml
prow/knative/cluster/400-sinker.yaml
prow/knative/cluster/400-tide.yaml
prow/knative/cluster/500-needs-rebase.yaml
prow/knative/cluster/500-status-reconciler.yaml
prow/knative/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

It's used to be plank was the reference, but now it's replaced by prow controller manager, updating it so it works
/assign @fejta @michelle192837 @e-blackwelder

Fixing prow autobump by using prow controller manager as reference

---

prow/prowjobs/kunit-review.googlesource.com/linux/OWNERS

It was suggested[1] that we take ownership over the Prow config for KUnit
GoB since most Prow people are not familiar with it. (It also helps the
Prow people find who to talk to if something goes wrong with KUnit Prow
config.)
Link[1]: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/570#pullrequestreview-516016316

Add OWNERS file for KUnit GoB instance

---

prow/knative/config.yaml

Sinker by default runs every hour, which is not very efficient

Knative prow: define the same sinker spec as oss prow

---

prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

Runs every 2 hours with 30 minute offset from the smoke test.

Add exposure notification verification server e2e test to Prow.

---

prow/knative/cluster/301-rbac.yaml
prow/knative/cluster/400-prow-controller-manager.yaml

See kubernetes/test-infra#19906 for more
context. Applying a similar change to our other Prow instances.

Update rbac for knative-prow.

---

prow/oss/cluster/monitoring/mixins/lib/config.libsonnet

The traffic of oss prow is not super high, got an alert today with the setting of 30 minutes, looking at prow and there is no problem at all

Relax oss prow alert: only alert after 60 minutes without webhook events

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This reverts commit 204e8693e333d02c75aba3d1a44248352e9cd283.
Pods stopped being scheduled after this bump; reverting

Revert "Bump oss-prow from v20201106-ea76c130fa to v20201112-00537d1bb4"

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This reverts commit c7f1863bcb0c2627d5a0a2f863922a04308c51bb.

Revert "Bump oss-prow from v20201106-ea76c130fa to v20201116-dbd60ab192"

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

It was a bad copy/paste from somewhere else, ymal lint check should be on the entire repo

Fix yamllint job scanning path

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml
prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

Runs presubmit.sh continuously like in presubmit

EN server: continuously running general tests

---

prow/prowjobs/google/exposure-notifications-server/en-server.yaml
prow/prowjobs/google/exposure-notifications-verification-server/en-verification-server.yaml

We've found the problem and can remove this now. Thanks!

Revert "EN server: continuously running general tests"

---

prow/knative/plugins.yaml

Enable cherrypicker plugin for `knative`, `knative-sandbox` and `google/knative-gcp`
/cc @chaodaiG @cjwagner

Enable cherrypicker plugin for Knative orgs

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Regular version taken from here: https://cloud.google.com/kubernetes-engine/docs/release-notes
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.16.13" found.
```

[ESPv2] Update GKE version

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Upgrade golang to latest stable 1.15 from 1.13 so that
- resolve the library difference, ex. quotation mark for [the url in the error](https://github.com/GoogleCloudPlatform/esp-v2/blob/e16dc8bc9830ebbb6333035613d23775cab0276e/src/go/util/url_util_test.go#L202) returned by `net/url`
- align with our [developer guide](https://github.com/GoogleCloudPlatform/esp-v2/blob/master/DEVELOPER.md#install-golang)

Upgrade golang to 1.15

---

prow/knative/cluster/monitoring/secrets/alertmanager-prow_secret.yaml
prow/oss/cluster/monitoring/secrets/alertmanager-prow_secret.yaml

Apparently the previous email recipient was not receiving email alerts, switch to google group should work

Prometheus alerts send to google group

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

/hold
Attempting to debug testgrid autobump. Not sure if this is all that is needed

Add missing ssh key secret to autobump testgrid jobs

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Trying out using the `KUBECONFIG` env var rather than merging all kubeconfigs into a single secret.
See the discussions [here](https://github.com/kubernetes/test-infra/pull/18695#discussion_r466087229) and [this issue](https://github.com/kubernetes/test-infra/pull/20417) for context. Our current pattern works reasonably well, but has the downside of not showing which clusters were added in the git history. Switching to using separate secrets and the `KUBECONFIG` envvar will give us the git history we want and avoid secret size limits down the road, but at the cost of making our deployment files harder to read and making the consumers of the kubeconfig implicit rather than explicit. This tradeoff didn't seem worth it at first, but does now in retrospect.
I've already created the new secret …

Register 'build-kubeflow' cluster with OSS-Prow.

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

autobumper.sh is broken and will not be able to bump itself out of being broken, so I am manually bumping the autobumper to the current k8s/test-infra image that has the fix.

Bump autobumper to working image

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

The testgrid autobump jobs are currently failing because the robot doing the bump does not have a fork of Testgrid. A fix has been landed in the generic autobumper to allow the robot to create the fork before doing the bump. I am bumping the generic_autobumper image to the latest version to hopefully fix the testgrid autobump jobs.

Update generic autobump image for testgrid bump job

---

prow/oss/cluster/monitoring/grafana_expose.yaml

The DNS entry was registered to be associated with the global static ip named , this makes grafana exposed on the domain oss-prow-monitoring.knative.dev

Expose prow monitoring dashboard

---

prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml

Switching to using workload identity instead.
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/81 binds the `test-jobs/default` k8s SA to the correct GCP SA

secrets-store-csi-driver-provider-gcp: remove secret

---

prow/oss/plugins.yaml

Copy/pasted from https://github.com/kubernetes/test-infra/blob/bddebf7eafa01069826beb90521e4638c47e53f1/config/prow/plugins.yaml, this step only enable trigger plugin for kubeflow repo, but not anything else, after this PR oss prow will be able to trigger prow jobs in kubeflow repos, but not taking actions
CC @Bodgy

Enable trigger plugin for kubeflow repos

---

prow/knative/plugins.yaml

As we discussed in https://knative.slack.com/archives/CCSNR4FCH/p1610649354006500, this will allow reviewers to add `lgtm` and `approve` labels with one single click.

Set review_acts_as_lgtm to true for lgtm plugin

---

prow/oss/cluster/monitoring/grafana_expose.yaml

These annotations seem to be required for the ingress to behave normally. Also by the way:
- Rename managedcertificate so that it's not the same name as the one used for deck.
- Remove subpath `/monitoring` as it's using a subdomain now.

Configure oss prow grafana exposure to match k8s prow settings

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

I don't think this arg is needed. Our tests keep breaking every month when an old version goes out of date. Let's just remove it.
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.17.13" found.
```

[ESPv2] Remove GKE version

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

We switched away from stable releases in #484 due to a versioning problem. Hopefully it does not exist anymore. This will reduce maintenance burden for us.

[ESPv2] Switch back to stable releases for GKE kubekins

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

`release/stable` uses k8s stable versions. But these are not available yet on GKE sometimes. Let's try using the GKE regular release channel.

[ESPv2] Switch kubekins versions to GKE regular release channel

---

prow/knative/plugins.yaml

This is based on TOC discussion, and community poll:
- blunderbuss: https://knative.slack.com/archives/C93E33SN8/p1613067143285100
- self-approve: https://knative.slack.com/archives/C93E33SN8/p1613067186285400
/hold

Disable blunderbuss, remove self-approve.

---

prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml
prow/prowjobs/kubeflow/testing/kubeflow-testing.yaml
prow/prowjobs/kubeflow/website/kubeflow-website.yaml

Move tests for website, gcp-blueprints and testing to oss prow as optional & skip_report

test(kubeflow): add tests for website , gcp-blueprints and testing

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Both knative and autobump jobs were pointing at the knative autobump config

Fix oss autobump job pointing at knative autobump config

---

prow/knative/cluster/500-cherrypicker.yaml

Add --github-token-path flag to cherrypicker

---

prow/oss/plugins.yaml
prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/OWNERS
prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml
testgrid/config.yaml

Adds configurations to use Prow as CI for https://github.com/grpc-ecosystem/grpc-httpjson-transcoding.
Configuration wise:
- Add a new presubmit and periodic job. Re-use the docker container configured in other jobs managed by our team.
- Re-use the `esp-v2` Prow cluster that our team self-hosts on GCP.
- Create a new testgrid dashboard.
Also configured the webhook, using a similar IP address and secret as our pre-existing project (esp-v2).

[grpc-transcoder] Add Prow setup for grpc-transcoder

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

/assign @chensun @zijianjoy @capri-xiyue 
context: I was working on https://github.com/kubeflow/pipelines/pull/5266 and noticed that some tests should be triggered but they were not, so I added those rules to run_if_changed.

test(kubeflow): better run_if_changed conditions

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

These changes are needed as a result of this PR https://github.com/kubernetes/test-infra/pull/20813

Fix command name being different for k8s-prow autobump image

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

/assign @zijianjoy @chensun 
Can you help me review?
Context:
https://github.com/kubeflow/pipelines/pull/5278/files#diff-aa26e66c26c946af954a32651055a721a96174ce3ccabacf16149e471075d80c failed mkp test postsubmit, but it didn't trigger the test in presubmit which it should

test(kubeflow): more accurate run_if_change for kubeflow-pipeline-mkp-test

---

prow/prowjobs/google/http_pattern_matcher/http-pattern-matcher.yaml

We use `main` instead of `master` for this new repository.

[http-pattern-matcher] Update branch name

---

prow/oss/cluster/monitoring/Makefile
prow/oss/cluster/monitoring/secrets/replace-secrets-from-gcp.sh

It's pretty hard to have make rules to exit based on wrapped subshell, turn it into a script and it should exit correctly

OSS prow monitoring secret: updated with a script instead of make rule

---

prow/oss/plugins.yaml

According to https://github.com/kubernetes/test-infra/issues/19896#issuecomment-724413115,
We want to restore the behavior of always requiring self approval.
/assign @chaodaiG @Ark-kun

config(kubeflow): kubeflow/pipelines require self approval for PRs

---

prow/oss/README.md
prow/oss/cluster/kubernetes-external-secrets_crd.yaml
prow/oss/cluster/kubernetes-external-secrets_deployment.yaml
prow/oss/cluster/kubernetes-external-secrets_rbac.yaml
prow/oss/cluster/kubernetes-external-secrets_service.yaml
prow/oss/cluster/monitoring/mixins/lib/config.libsonnet
prow/oss/cluster/monitoring/mixins/prometheus/external_secret_alerts.libsonnet
prow/oss/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
prow/oss/cluster/monitoring/prow_servicemonitors.yaml
prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml

This was enabled in upstream and working: https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md

Oss prow: enable secret managed by kubernetes external secrets

---

prow/knative/README.md
prow/knative/cluster/200-serviceaccounts.yaml
prow/knative/cluster/500-kubernetes-external-secrets_crd.yaml
prow/knative/cluster/500-kubernetes-external-secrets_deployment.yaml
prow/knative/cluster/500-kubernetes-external-secrets_rbac.yaml
prow/knative/cluster/500-kubernetes-external-secrets_service.yaml
prow/knative/cluster/monitoring/mixins/lib/config.libsonnet
prow/knative/cluster/monitoring/mixins/prometheus/external_secret_alerts.libsonnet
prow/knative/cluster/monitoring/mixins/prometheus/prometheus.libsonnet
prow/knative/cluster/monitoring/prow_servicemonitors.yaml

This was enabled in upstream and working: https://github.com/kubernetes/test-infra/blob/master/prow/prow_secrets.md

Knative prow: enable secret managed by kubernetes external secrets

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

The version pointed by `gke-default` is unavailable. Go back to use `release/stable`.

Revert "[ESPv2] Switch kubekins versions to GKE regular release channel"

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

The [`gke-channel-regular`](https://source.corp.google.com/piper///depot/google3/production/borg/cloud-kubernetes/config/gke_versions.textpb;l=36-44;rcl=368927661) should be good. The current 1.18.16 is available on [our project](https://screenshot.googleplex.com/75paxFM6nsY7cyF).

Switch gke version to channel regular

---

prow/oss/cluster/kubernetes_external_secrets.yaml

These secrets were created from google-oss-robot account, and were already stored in oss-prow project

Add external secret for github oauth2 secrets in preparation for private deck deployment

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Our e2e gke jobs still failed, because prow-pod-utils@cloudesf-prow-build.iam.gserviceaccount.com will need access to gke-release-staging for the channel version. Try ci/latest-1.18.

Try ci/latest-1.18

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This is required for updating dependencies from k8s/test-infra, see failed test at https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/GoogleCloudPlatform_oss-test-infra/785/pull-test-infra-go-test/1384690825857863680

Update presubmit test image to use go1.15

---

prow/oss/cluster/cluster.yaml

Legacy webhook endpoints still use ip address instead of domain name, which failed to be routed by ingress.

Remove host from oss prow ingress

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

This reverts commit 5621aa6b9aecf4f089423876799b205719d3bbac.
b/185946962: the `gke-channel-regular` should be working after the prow build cluster SA has good permission.

ESPv2: use `gke-channel-regular`

---

prow/oss/cluster/deck_private_deployment.yaml

Update to the latest image
explicit cookie expiration in 23 hours
use chaotoppicks org for faster debug turnaround

Fix private deck deployment with oauth2 fixes

---

prow/oss/cluster/deck.yaml

Once this merges I'll bind the SAs with workload identity and then make another PR to switch deck to use this SA and delete the old one. Once that merges I'll delete the old SA. This should avoid any downtime.

Add a separate SA for public Deck to distinguish from other control plane components.

---

prow/oss/cluster/deck.yaml

Follow up to https://github.com/GoogleCloudPlatform/oss-test-infra/pull/821.  `deck-public` SA has been bound.

Switch public Deck to use new SA.

---

prow/oss/config.yaml
prow/oss/plugins.yaml

/hold
These are the next steps assuming the POC is approved on Monday. Before this is merged the bot needs to have admin access to the org and SSH deploy keys must be configured.

Onboard looker org.

---

prow/oss/cluster/deck_private_deployment.yaml

This was missing and preventing build logs from streaming. The error was hidden by our logging filters because it wasn't from logrus.

Update deck-private RBAC.

---

prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

As discussed among prow oncalls, it's agreed that:
- OSS prow has been pretty stable lately
- All errors were caught by automated alerts
This gives us enough confidence to enable automated continuous deployment of oss prow, the steps are the same as https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/2539-continuously-deploy-k8s-prow

Automated continuous deployment of oss prow

---

prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml
testgrid/config.yaml

Running the e2e tests at least once a day will help handle any dependency/test issues as they arise. This PR will resolve [Secrets CSI - Issue 103](https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/103). 
The periodic job was set up following the examples in the [Prow Test Jobs Examples doc](https://github.com/kubernetes/test-infra/blob/master/config/jobs/README.md#job-examples) and the [grpc-httpjson-transcoding](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml) setup.

Set up a periodic test job to run e2e tests against main once a day

---

prow/knative/cluster/build/600-kubernetes_external_secrets.yaml

Fixes https://github.com/knative/test-infra/issues/2775 and https://github.com/knative/test-infra/issues/2760
The current secret configuration for the knative prow job is tightly coupled with the ownership of the build cluster, which can be loosened by the kubernetes external secret. The installation of the CRDs and the controller has been recently finished (https://github.com/GoogleCloudPlatform/oss-test-infra/pull/807). This PR is a follow-up task for the s390x knative test. 
MAINTAINERS, **please** delete the existing secret `s390x-cluster1` before merging this.

Add external secret from build cluster for knative

---

prow/knative/config.yaml
prow/knative/plugins.yaml

See https://github.com/GoogleCloudPlatform/oss-test-infra/pull/714 and preceeding:
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/711
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/709 
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/702
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/659
This also carries over the "GitHub Review = LGTM + Approve" from this PR ([conversation](https://knative.slack.com/archives/CCSNR4FCH/p1610649354006500)):
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/667
Fixes https://github.com/knative/test-infra/issues/2752

Undo #714 and use prow /lgtm and /approve

---

prow/knative/cluster/build/600-kubernetes_external_secrets.yaml

This PR is to add an additional external secret for the knative e2e test against the s390x test machine.

Add external secret for knative build cluster

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

See https://github.com/kubernetes/test-infra/blob/6b3c4eecea921dd6598121b01a945387c3347148/testgrid/cmd/configurator/main.go#L86 for usage and https://testgrid.k8s.io/wg-k8s-infra-k8sio#ci-k8sio-audit for example output

Add prow job config path on testgrid

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Context: #832
The newly-created bucket has bucket-wide permissions, causing the `--world-readable` flag, which sets a file-level permission, to fail.
https://oss-prow.knative.dev/view/gs/oss-prow/logs/post-oss-test-infra-create-testgrid-config/1397600094118744064
Prow job: https://oss-prow.knative.dev/?job=post-oss-test-infra-create-testgrid-config

TG config upload: stop setting file-level permission

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

xref #832
Adds test to ensure that Configurator will be able to generate the TestGrid configuration before it does it as a postsubmit

Add TestGrid config presubmit test

---

prow/oss/plugins.yaml

As we (Notebooks WG leads) discussed https://github.com/kubeflow/kubeflow/issues/5953 we'd like to explicitly require self-approval for our PRs.
This is also the case for the other repos of the Kubeflow org.
cc @yanniszark @elikatsis @StefanoFioravanzo @thesuperzapper @Bobgy

Require self-approval for kubeflow/kubeflow

---

prow/oss/cluster/crier.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Note: this will not work until https://github.com/kubernetes/test-infra/pull/22386 is in oss-prow, which should happen on Monday 06/07. Also the secret knative-slack-token is not in either, I'll create a separate PR adding this secret
/hold

Automatically posting knative prow deploy message on slack

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

added kfp presubmit v2 test

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Add build cluster kubeconfig for blueprints

---

prow/tests/jobs_test.go

This is generally not expected other than trusted directory where OWNERS are prow maintainers or hidden repo owners

Add a prow job config test checking for jobs running on hidden repos

---

prow/prowjobs/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/secrets-store-csi-driver-provider-gcp-config.yaml

Set envvars so that the periodic job will use the `main` branch instead of `PULL_PULL_SHA`:
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/103
blocked on https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/pull/115

secrets-store-csi-driver-provider-gcp: configure periodic envvars

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml
testgrid/config.yaml

Our release images are built from the master head(we relied on continuous build job before) so we need a post submit job to build it.

Add postsubmit jobs building image for release

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This had been piloted on k8s prow for 2 months https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/2539-continuously-deploy-k8s-prow, and oss prow for 1 month https://github.com/GoogleCloudPlatform/oss-test-infra/pull/851.
Both were proven to be pretty reliable, so moving forward on knative prow

Knative prow: automated deployment

---

prow/oss/cluster/crier.yaml

so that it can post slack message when knative prow is automatically updated
/hold
This will cause prow failure, will only work after changes from https://github.com/kubernetes/test-infra/pull/22600 is in oss prow

Add a slack worker on oss prow

---

prow/oss/cluster/crier.yaml

This reverts commit ea3f66829c8527945226b62de50081fb77cfbacf.
Got an error `slackreporter is enabled but has no config`

Revert "Add a slack worker on oss prow"

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/monitoring/prow_podmonitors.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/tide.yaml

This PR should be sufficient to begin collecting metrics via Workload Metrics and it should not impact the existing monitoring solution. The `PodMonitor` resources parallel the Prometheus-Operator `ServiceMonitor` resources, but match on the pods instead of services. I've updated deployment files to name the container ports in the same way the services name them.
/assign @chaodaiG @mpherman2

Add Workload Metrics PodMonitor resources for oss-prow components.

---

prow/oss/config.yaml

This is an internal group, but the majority of OSS Prow users are Googlers so I think it is worth advertising here.
/assign @mpherman2

Add announcement banner promoting prow-announce@google.com group.

---

prow/oss/cluster/monitoring/prow_podmonitors.yaml

This PodMonitor is causing issues with the monitoring services. It has been recommended that we temporarily remove it so that we can continue the demo.
Once this PR merges I'll run `kubectl delete -n prow-monitoring podmonitor kubernetes-external-secrets`.
/assign @mpherman2 @fejta

Temporarily remove problematic PodMonitor.

---

prow/oss/cluster/prow-controller-manager.yaml
prow/oss/config.yaml

/hold
This won't work until version v20210730-5757a5d200, which was from https://github.com/kubernetes/test-infra/pull/23068

oss-prow reporting build clusters statuses in GCS

---

prow/oss/config.yaml

we want to permit use of spyglass against our custom job logs in this bucket

add gcp-guest bucket for spyglass

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Fixes https://oss-prow.knative.dev/view/gs/oss-prow/logs/post-testgrid-deploy-canary/1423772252528185344

Use testgrid variant of gcloud-bazel

---

prow/oss/terraform/main.tf
prow/oss/terraform/modules/alerts/main.tf
prow/oss/terraform/modules/alerts/variables.tf

This is on top of #995 
Wasn't able to find an equivalent of `up` from prometheus https://github.com/GoogleCloudPlatform/oss-test-infra/blob/cd38a59352b0225b4ebfb5601089fa6edfa4ab83/prow/oss/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet#L11, catching pod crashlooping might be a good starting point
/hold
more to be added

Terraform alert on pod crashlooping

---

prow/oss/config.yaml

There are 9 jobs using default cluster:
- 6 from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml, none of these 6 jobs seem to need extra GCP permissions.
- 1 from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml, will need to monitor.
- 1 from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/kunit-review.googlesource.com/linux/kunit-linux-config.yaml, will need to monitor.
- 1 from https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-images.yaml, this was already fixed

All jobs using default build cluster use WI by default

---

prow/oss/cluster/hook.yaml

Hook is responsible for triggering inrepoconfig jobs, it figures out how to run it by cloning the entire target repo, which could be throttled when encounters large repo at scale. Increasing the replicas should be able to help

Increase hook replicas to 6 and set resource requests

---

prow/oss/cluster/hook.yaml

For consistency reason with other prow instances, also makes the service more resilient

Add liveliness and readinessprobe for hook

---

prow/oss/terraform/modules/alerts/probers.tf

These two fields are the ones that cause terraform complaining something is changed when there is no config change at all

Add optional fields to avoid noise from terraform plan

---

prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml

test-infra-trusted cluster is the test-pods namespace in oss-prow cluster, creating this service account so that jobs using this cluster can use this SA by default

Create SA for running jobs in test-infra-trusted cluster

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Add build cluster kubeconfig for looker-int-test

---

prow/knative/config.yaml

Some recent change in k8s.io/test-infra made it a hard requirement to have the branchprotector config in the Prow core config file - https://prow.knative.dev/job-history/gs/knative-prow/logs/ci-knative-test-infra-branchprotector. This PR is moving the Knative branchprotector config file in https://github.com/knative/test-infra/tree/main/config/branch_protector

Move branchprotector config for Knative to the core Prow config file

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/sub.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml

This reverts commit d9ed21fc1145f9eab23cbe48586cf87802e45149.
The bump failed inrepoconfig for pubsub triggered job:
```
error: "failed to clone repo for "looker/helltool": no Fetch implementation exists in the v1 repo client"
```

Revert "Bumping oss-prow"

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/sub.yaml
prow/oss/cluster/tide.yaml

v1beta1 is deprecated v.1.22+ as https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122, updating it before we ran into it

Update rbac.authorization.k8s.io to v1

---

prow/knative/cluster/301-rbac.yaml
prow/knative/cluster/400-prow-controller-manager.yaml
prow/knative/cluster/build/301-rbac.yaml

v1beta1 is deprecated v.1.22+ as https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122, updating it before we ran into it

Knative prow: update rbac.authorization.k8s.io to v1

---

prow/oss/cluster/deck_private_deployment.yaml

We fixed the issue with labeling Prowjobs and created some integration tests to confirm this works as expected.
/hold

Switch Deck Private instance from hidden only to tenantID

---

prow/oss/cluster/crier.yaml

This includes updating crier to use git cache client https://github.com/kubernetes/test-infra/pull/23589, should speed up crier reporting

bump crier to v20210914-d9fade61b4

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/tide.yaml

These are components that might experience high cpu and disk I/O for inrepoconfig lookup, move them to a dedicated nodepool, so that they can be scheduled on a node with no neighbor, and the availability is guaranteened

oss-prow: move crier and tide to dedicated nodepool

---

prow/knative/config.yaml

Before we can [remove knative milestone maintainers](https://github.com/knative/community/issues/92) role in:
https://github.com/knative/community/pull/768
We need to remove it from here first.

remove Knative Milestone Maintainers

---

prow/oss/cluster/crier.yaml

Crier started to use inrepoconfig since https://github.com/kubernetes/test-infra/pull/23484 on 09/10, rolling back to before this date can unblock crier

Roll back crier to v20210908-3a373c2cdd

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/tide.yaml

This reverts commit 15ab02e219087834bb850e5a8bf9cc5dba2f96b5.
These were not needed, as crier is not doing inrepoconfig any more, and tide is not throttled either

Revert "oss-prow: move crier and tide to dedicated nodepool"

---

prow/oss/cluster/crier.yaml

https://github.com/kubernetes/test-infra/pull/23606 allows opt out of crier commenting on PRs, bumping crier with this change to help lower github token usage

Bump crier for allowing skip comment on PR

---

prow/oss/config.yaml

Opts out of this comment on PRs, for example:
This feature doesn't really provide too much value, but appears to be using lots of github tokens from prow robot account. Opting out can avoid depletion of prow robot account token, which might fail prow components that rely on github APIs
/hold

Opting out looker/helltool from bot commenting job failure

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/sub.yaml
prow/oss/cluster/tide.yaml

Hoping to get 2 things out of this.
- Tracking down some token usage that we are having trouble identifying
- Switch to GitHub's new, more secure personal access token format.
This token has the same scopes, is for the same bot, and is under the same secret key (`oauth`).

Rotate Prow deployments to a new oauth token.

---

prow/oss/config.yaml

Fix status check links to go to private front end for blueprints team
@assign @chaodaiG @cjwagner

Blueprints tests redirect to private front end

---

prow/knative/cluster/build/400-boskos-reaper.yaml

With this small change, Boskos Janitor will start clean up the GCP projects 11 minutes (which was 30 minutes by default) after the Prow jobs are terminated, which'll help save some resources.

Update Knative Boskos reaper expire to 11min to recycle the resources more efficiently

---

prow/oss/cluster/sub.yaml

The new inrepoconfig caching feature has been deployed with
PR #1146 (approximately ~2:55 PM PDT on 2021-09-27). Having multiple
replicas hurts cache efficiency because each replica maintains its own
in-memory cache.

Decrease Sub replicas from 10 to 2

---

prow/oss/terraform/modules/alerts/main.tf

This will make the alerts less sensitive to sudden increases in consumption at the cost of alerting later.
/assign @listx @mpherman2

Increase ratelimit exhaustion prediction alert alignment window from 10m to 15m.

---

prow/oss/cluster/cluster.yaml
prow/oss/cluster/crier-ghapp.yaml
prow/oss/cluster/hook-ghapp.yaml

Part of #1171 
This PR only sets up the ground for GitHub app workflow, prow won't take any action even if an org/repo installed the prow app, until they are added to allowlist with `- --github-enabled-org=<ORGREPO>`.
For easier code review this PR is broken down into 2 commits:
1. Copy/paste crier.yaml and hook.yaml
2. Change the new files to work with GitHub app

Hook, crier and ingress set to work with GitHub app

---

prow/oss/cluster/crier-ghapp.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/hook-ghapp.yaml
prow/oss/cluster/hook.yaml

Note that there will be some minor impacts:
1. there will be a few seconds that webhooks are double handled, so prow might do something repeatedly
2. prow will not recognize the comments it left before, so on existing PRs there will be two prow comments instead of one

Opt in oss-test-infra for GitHub app authentication

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

/assign @chaodaiG @listx 
This is needed to unblock https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1202.
It has to be in a separate PR like this because we are not using in-repo config for this repo.

Bump pull-test-infra-go-test to go version 1.16.

---

prow/oss/terraform/modules/alerts/main.tf

Whoops, I put the `~` on the wrong side. This is already deployed.
/assign @chaodaiG @listx @mpherman2

Fix regex equallity typo in rate limit exhaustion prediction.

---

prow/oss/cluster/crier-ghapp.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/hook-ghapp.yaml
prow/oss/cluster/hook.yaml

This is part of https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1171, I have requested installation of all repos under GoogleCloudPlatform that are currently using prow, and so far it seems like they are all approved. Trying this out on testgrid repo, will migrate others all at once if this proves to be working

testgrid repo uses github app for authentication

---

prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml

I don't think this will make a difference, but should be done for consistency. May be important if we start caring about naming collisions later or for some subtle reasons.
/hold

Make helltool checkconfig job include core job config.

---

prow/oss/config.yaml

Managed hmac tokens are for setting up webhooks from legacy prow robot token, they are not required since GoogleCloudPlatform has migrated to use prow GitHub app for setting up webhooks

Stop managing hmac tokens for GoogleCloudPlatform repos

---

prow/oss/config.yaml

Managed hmac tokens are for setting up webhooks from legacy prow robot token, they are not required since kubeflow has migrated to use prow GitHub app for setting up webhooks

Stop managing hmac tokens for kubeflow repos

---

.prow/presubmits.yaml
prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml

Depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1260 Only the latest commit is unique to this PR.
/hold
/cc @2nd-half @bharathkkb 
Once this is merged we'll get signal about any existing unknown field errors in the in-repo config. After we've addressed the errors we can enable these options for the main checkconfig presubmit.

Add checkconfig canary jobs for looker and blueprints to try out unknown field validation of in repo config.

---

prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml

/assign @listx @mpherman2 
/cc @bharathkkb 
Whoops.

Fix default branch name for blueprints checkconfig canary.

---

prow/oss/terraform/main.tf
prow/oss/terraform/modules/alerts/main.tf
prow/oss/terraform/modules/alerts/probers.tf
prow/oss/terraform/modules/alerts/variables.tf

Without this, `uptime_checks` configured in scoped projects will also be included, but we only care about the `uptime_checks` we are explicitly enumerating here.

Update uptime probe alerts to ignore extraneous uptime_checks.

---

prow/oss/terraform/main.tf
prow/oss/terraform/modules/alerts/main.tf
prow/oss/terraform/modules/alerts/probers.tf
prow/oss/terraform/modules/alerts/variables.tf

Depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1267
/hold
The first commit is from the other PR, just wanted to avoid a rebase.

Enable cloud monitoring alerts for knative-prow.

---

prow/oss/terraform/main.tf
prow/oss/terraform/modules/alerts/main.tf
prow/oss/terraform/modules/alerts/probers.tf
prow/oss/terraform/modules/alerts/variables.tf

Depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1268 which depends on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1267
/hold
First two commits are from those PRs.

Add alerting config for istio-testing.

---

prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml

/assign @listx @mpherman2 
Clone is failing because I missed this.

Add missing clone_uri for looker checkconfig canary.

---

prow/oss/config.yaml

The performance dashboards labeled Frontend tests as dashboard 8195 but they're actually 8194, likewise Backend tests are on dashboard 8195 but were labeled as 8194. This pull request fixes this labeling in the prow robot message for looker pull requests.

Looker performance tests dashboards typo fix

---

prow/oss/terraform/main.tf
prow/oss/terraform/modules/alerts/variables.tf

`terraform validate` didn't catch
1. the invalid host names
2. the type problem. `for_each` only works for sets and maps, not lists. (I'm surprised this wasn't caught)
I've already applied the config with these changes.

Fix blackbox probe terraform config.

---

prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml

This change has been tested with a canary periodic job to confirm there are no existing problems that would cause the new stricter validation to block PRs.
/cc @bharathkkb 

Make blueprints checkconfig presubmit include strict validation.

---

prow/prowjobs/private-inrepoconfig-configcheck/looker/helltool/hellotool.yaml

/hold
This change has been tested with a canary periodic job to confirm there are no existing problems that would cause the new stricter validation to block PRs: https://oss-prow-private.knative.dev/?job=ci-looker-helltool-validate-prow-yaml-canary
@2nd-half 

Make looker checkconfig presubmit include strict validation.

---

prow/oss/cluster/crier-ghapp.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/hook-ghapp.yaml
prow/oss/cluster/hook.yaml

The prow app was installed in http_pattern_matcher and bms-toolkit repos

github/google org switches to use GitHub app for prow

---

prow/oss/config.yaml

Managed hmac tokens are for setting up webhooks from legacy prow robot token, they are not required since google has migrated to use prow GitHub app for setting up webhooks
/hold
Merge this after #1277

Stop managing hmac tokens for google repos

---

prow/oss/config.yaml

Managed hmac tokens are for setting up webhooks from legacy prow robot token, they are not required since grpc has migrated to use prow GitHub app for setting up webhooks

Stop managing hmac tokens for grpc repos

---

prow/oss/terraform/modules/alerts/main.tf

Whoops, I didn't fix this alert all the way when migrating to a single metrics project.

Fix the webhook-missing alerts to only count webhooks from the relevant instance.

---

prow/oss/config.yaml

Now that no oss-prow tenant uses PAT, there is no more webhooks to be managed, removing entirely to avoid confusion. This change doesn't affect webhooks set up by GitHub app

Remove all managed webhooks

---

prow/oss/cluster/tide.yaml

Now that all prow tenants have migrated to use GitHub apps, migrate tide to use app authentication should be no blockers.
Note that tide doesn't get the tokens benefits as hook and crier, so we might still run into rate limit issue when there are lots of repos enable tide. However it shouldn't be worse than today

Migrate tide to use GitHub app

---

prow/oss/cluster/sub.yaml

Now that all prow tenants have migrated to use GitHub apps, migrate sub to use app authentication should be no blockers.
The only place where GitHub authentication is used in sub is for cloning repos to figure out inrepoconfig prow jobs, this had been proved to be working in hook, the risk should be low

Migrate sub to use GitHub app

---

prow/oss/cluster/crier-ghapp.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/hook-ghapp.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/monitoring/prow_podmonitors.yaml

Now that everything has migrated, crier and hook deployments that use PAT are no longer serving any traffics. Remove them so that we don't need to do the --enabled-repos and --disabled-repos trick any more

Oss prow: crier and hook use GitHub app only

---

prow/oss/cluster/cluster.yaml

This was missing from previous PR, and hook didn't work. Prow cluster is fixed temporarily with https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1299. We can choose merging either that one or this PR

Webhooks from prow app send to hook

---

prow/pj-on-kind.sh
prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml
testgrid/config.yaml

This configures a new job that will run the module tests in `cli_tools_test/module`. They're configured using the recommendation from  [jobs.md](https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md):
> A useful pattern when adding new jobs is to start with always_run set to false and skip_report set to true. Test it out a few times by manually triggering, then switch always_run to true. Watch for a couple days, then switch skip_report to false.

compute-image-tools: Add presubmit for module tests

---

prow/oss/cluster/sub.yaml

This reverts commit 903422627e7cda928d286fa9dc11a998cded914c.
The initial bug was fixed in https://github.com/kubernetes/test-infra/pull/24317, should work now

Revert "Revert "Migrate sub to use GitHub app""

---

prow/oss/oss-autobump-config.yaml

It's proved to work as https://github.com/kubernetes/test-infra/pull/24414

Oss-prow autobump PR not assigned to anyone

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

This fixes the failure in the [file_inspection_test](https://oss-prow.knative.dev/view/gs/oss-prow/logs/cli-tools-postsubmit-module-tests/1461800655155892224) from https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1790.
`exec: "gcsfuse": executable file not found in $PATH`
Testing:
- Ran `pj-on-kind.sh cli-tools-postsubmit-module-tests` using a locally-built image.
@dntczdx

Use cli-tools-module-tests image for import/export module tests

---

prow/oss/cluster/sub.yaml

This reverts commit 9c07c14d34dff7acb18b2600a71363bea91740b0.
Third attempt, previous bug fixed in https://github.com/kubernetes/test-infra/pull/24424.
@2nd-half , is there a script that I can use for smoke testing?
/hold

Revert "Revert "Revert "Revert "Migrate sub to use GitHub app""""

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

OS Login tests only work in one project - we will start by running them separately

gcp-guest: exclude oslogin from CIT

---

prow/oss/config.yaml

We should revert this after the deadline passes.

add banner for Prow User Survey (2021 year-end)

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Enable snapshot test to enforce validation.
https://github.com/kubeflow/pipelines/blob/master/manifests/gcp_marketplace/test/presubmit.sh

pipelines: Add gcp_marketplace presubmit test

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

I found that the presubmit test has failed because it cannot find the presubmit file:
https://github.com/kubeflow/pipelines/pull/7137

fix(pipelines): file not found for marketplace snapshot test

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

The test doesn't generate any log, try to combine two commands to test it out.
https://pantheon.corp.google.com/storage/browser/_details/oss-prow/pr-logs/pull/kubeflow_pipelines/7153/kubeflow-pipeline-mkp-snapshot-test/1479705100409638912/build-log.txt;tab=live_object
@Bobgy

pipelines: Merge two commands to one line for mkp-snapshot-test

---

prow/prowjobs/kubeflow/gcp-blueprints/kubeflow-gcp-blueprints.yaml

Currently any PR on kubeflow/gcp-blueprints will trigger postsubmit test during PR creation. Therefore we should restrict to only the master branch and release branches.

gcp-blueprints: Run postsubmit only when it is master branch or release branch

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

golang:1.17.6-alpine3.15 doesn't have `bash` but `/bin/sh`

test(pipelines): fix kubeflow-pipeline-backend-test

---

prow/knative/cluster/400-ingress.yaml
prow/oss/cluster/cluster.yaml

Necessary for upgrading the cluster to 1.22+

Upgrade ingresses to networking.k8s.io/v1.

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

/assign @zijianjoy 
Sorry for the back and forth. Even our go unit test requires `gcc` that the alpine image doesn't have.
```
+ go test -v -cover ./backend/...
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH
```
Verified that this image has `/bin/bash`, `gcc`, `git`, etc.

test(pipelines): use golang:1.17.6-bullseye for backend presubmit

---

.prow/presubmits.yaml
prow/knative/plugins.yaml

This PR (https://github.com/knative/test-infra/pull/3044) changed the Knative ProwJob config path which broke the config updating logic, the checkconfig job in this repo, and subsequently blocked [the Prow update](https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1439).
/assign @chizhg 
Please note that any config changes since the break have not been applied and a new change will be required to pick up the changes that were dropped.

Fix Knative job config path.

---

prow/oss/plugins.yaml
prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml

[compute-daisy](https://github.com/GoogleCloudPlatform/compute-daisy) is the new home for Daisy. This PR emulates the current behavior in [compute-image-tools](https://github.com/GoogleCloudPlatform/compute-image-tools); a subsequent PR will remove the daisy presubmits from compute-image-tools.
- Ran `pj-on-kind` for the three new jobs. 
@hopkiw @adjackura

compute-daisy: Onboard for presubmits

---

prow/oss/cluster/deck_blueprints_deployment.yaml

We want to allow an additional GH team to view Prow logs.

chore: allow blueprint-solutions-contrib access to prow frontend

---

prow/oss/config.yaml

This enables tide for [compute-daisy](https://github.com/GoogleCloudPlatform/compute-daisy)
@adjackura @hopkiw

compute-daisy: Use tide for merging PRs

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml

This adds e2e periodic tests for compute-daisy.
- Ran pj-on-kind and confirmed that the `junit.xml` file was created in `/artifacts`:
```
/mnt/disks/prowjob-out/compute-daisy-e2e/1491857579528163328
├── artifacts
│   └── junit.xml
├── build-log.txt
├── finished.json
└── started.json
```
@hopkiw @adjackura

compute-daisy: Add periodic e2e test

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

We're moving the Daisy code from [compute-image-tools](https://github.com/GoogleCloudPlatform/compute-image-tools) to [compute-daisy](https://github.com/GoogleCloudPlatform/compute-daisy).
Presubmits for the new repo: [compute-daisy.yaml](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml)
@hopkiw @adjackura

Remove presubmits for daisy from compute-image-tools

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

* fix one-space indentations
* remove ARTIFACTS environment variable
* specify command for each periodic job - bypassing wrapper!

gcp-guest: add legacy periodics commands

---

prow/knative/config.yaml

Signed-off-by: Paul S. Schweigert <paulschw@us.ibm.com>
xref: https://github.com/knative/test-infra/pull/3140
Previously, only the knative org IDs were being used. This caused an
error when trying to rerun jobs in the knative-sandbox org (the team ID
was invalid, because the ID in knative did not match the ID in sandbox).
This PR updates the rerun_auth-configs to use the team slugs instead.
The teams are now identified by a combo of org and slug (which should
alleviate the problem above) and has the added benefit of being more
explicit on which team is being used (don't have to double check that
the ID is the right ID for the team).
See Slack discussion here: https://knative.slack.com/archives/C03545VN9KK/p1646761295715509

Updates rerun auth to use slugs instead of ids

---

prow/knative/config.yaml

The current Prow has a bug for checking the rerun auth permissions for the periodic Prow jobs, when configured with `org` name as the key. For Knative, we don't really need that since we should allow the team members to rerun **all** Prow jobs, so this PR changes it back to `*`.
/cc @chaodaiG

Fix the rerun_auth_configs for Knative

---

prow/knative/cluster/build/600-kubernetes_external_secrets.yaml

This PR is to add 2 additional external secrets named `server-list` and `ci-script` for the knative e2e test against the s390x test machine.
We are currently refactoring the CI structure. Another PR will come for the deletion of the existing 2 secrets after the improvement is finished.

Add 2 external secrets for knative build cluster

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

We're seeing tests fail in `compute-image-test-pool-001` with the message `Quota 'SSD_TOTAL_GB' exceeded.  Limit: 40000.0 in region us-central1.` cleanerupper is running, and when I run it manually it deletes more resources and tests pass for awhile.
https://testgrid.k8s.io/googleoss-gcp-guest#cleanerupper

cleanerupper: Run every hour

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

Our build cluster is running out of memory when running this suite, which is causing a cascade of retries that's causing other suites to fail. While we update the build cluster, I'd like to disable this suite.
More info: https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1533

disable ci-images-import-export-cli-e2e-tests

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

In https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1536, we disabled the `ci-images-import-export-cli-e2e-tests` test suite while we upgraded our k8s build node pool. We finished the upgrade, so this re-enables the suite.
Additionally, this tunes the timeout period for long-running suites. The values are from historically successful runs on the old prow cluster, which did not enforce a timeout. Here's an example failure message that we're seeing:
```
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2022-03-21T00:09:35Z"}
```
Source: …

Re-enable import/export tests

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

- In https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1544, I missed adjusting the timeouts for the OVF tests. 
- The v2v tests are historical and no longer required -- we added them to assist migrate for compute engine when they were developing their product.

Increase timeout for OVF tests; remove v2v tests

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

In https://github.com/GoogleCloudPlatform/guest-test-infra/pull/422 we started publishing cleanerupper to `gcr.io/gcp-guest`.

use gcr.io/gcp-guest for cleanerupper

---

prow/knative/config.yaml
prow/knative/plugins.yaml

https://github.com/google/knative-gcp has been in maintenance mode and hasn't received new commits for more than 6 months. With Knative migrated to GitHub app, the CI/CD flows get broken and do not have strong incentives to get fixed.
This PR removes all the Prow config for google/knative-gcp for now. If in the future it turns out the maintainers of this project still need them, they can add them back.

Remove Prow config for google/knative-gcp

---

prow/knative/cluster/400-crier.yaml
prow/knative/cluster/400-hook.yaml
prow/knative/cluster/400-ingress.yaml

The GitHub app is at https://github.com/apps/knative-prow, and has already been installed for `knative` and `knative-sandbox` org.
Please note I'm using a brutal way to do the migration during the off-hours to make the migration easier and less disruptive. The config changes have already been applied on the Knative Prow cluster and have been tested at https://github.com/knative/test-infra/pull/3197.
Sorry if the migration triggered false alerts.

Migrate Knative Prow to a GitHub app

---

prow/knative/cluster/400-tide.yaml

This was missed in my last PR to migrate Knative Prow to a GitHub app.
/cc

Move Knative Tide to authenticate as a GitHub app

---

prow/oss/config.yaml

The `create_build_cluster.sh` script from the [onboarding guide](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/onboarding.md) prompted me to update this file.

Add plank config for compute-image-import-prow

---

prow/oss/cluster/kubernetes_external_secrets.yaml

Generated by running this script: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/create-build-cluster.sh

Add external secret from build cluster for compute-image-import

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/deck_private_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Generated by running this script: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/create-build-cluster.sh

Add build cluster kubeconfig for compute-image-import

---

prow/prowjobs/GoogleCloudPlatform/compute-image-import/OWNERS
prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml
testgrid/config.yaml

We're splitting the jobs related to import/export from [gcp-guest](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/GoogleCloudPlatform/gcp-guest) to a new directory.
This PR sets up the relevant jobs in the new directory. Once I confirm the new jobs are working, I'll remove the old jobs from `gcp-guest`.

Onboard compute-image-import's jobs

---

prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml

The job `compute-image-import-postsubmit-module-tests` currently isn't running: https://testgrid.k8s.io/googleoss-compute-image-import#module-tests . After debugging with pj-on-kind, I found that it was incorrectly configured: the repo `GoogleCloudPlatform/compute-image-import` uses the branch `main` instead of `master`.
Additionally, this removes a label which we aren't using for this cluster.

Compute image import: Use main branch

---

prow/oss/cluster/cluster.yaml

I don't expect oauth to work for the private front end until we've updated the oauth cookie domain.
/hold

Configure ingress and managed certs for gprow.dev domain.

---

prow/oss/config.yaml

This feature was added as of https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1594 and already deployed on oss prow. configure this for trusted cluster for testing purpose, will do this for other clusters if proved to work
/cc @cjwagner @mpherman2 @listx

Configure deck to display pod link from trusted cluster

---

prow/oss/config.yaml

This the the last remaining build cluster that we know which project it's from.
/cc @cjwagner @mpherman2

Add pod link template for default cluster

---

prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_private_deployment.yaml

When this merges I'll also complete the following:
/hold

Adjust oauth config for new gprow.dev domains.

---

prow/oss/config.yaml

Related: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1600
Following recommendation to enable pod detail link in the Prowjob UI. Here is an example of link:
`https://console.cloud.google.com/kubernetes/pod/us-east1-d/kf-ci-v1/test-pods/070adbfe-ccc7-11ec-b4ba-3ae2d8058ce3/details?project=kubeflow-ci`
We are using kubeflow-ci project, and the cluster name is kf-ci-v1, location is us-east1-d. 
We need to validate this change.

(kubeflow): Add pod link template for kf-ci-v1 cluster

---

prow/oss/config.yaml

Fix comment in https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1604

(pipelines): Fix cluster name to `build-kubeflow` for pod link

---

prow/oss/create-build-cluster.sh
prow/oss/gencred-refresher/gencred-refresher.yaml
prow/oss/serviceaccounts/GoogleCloudPlatform_oss-test-infra_serviceaccounts.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This is part of https://github.com/kubernetes/test-infra/issues/25993. TLDR: gencred generated token lasts at most 2 days, and after 2 days prow will lose access to build cluster unless someone manually run gencred again. This PR automates the rotating
/cc @cjwagner @listx

Onboarding build cluster also sets up gencred refreshing

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

v2 sample tests are failing on `sdk/release-1.x` branches (example: https://github.com/kubeflow/pipelines/pull/7786#issuecomment-1137584977) because the required script does not exist on those branches. 
We do not need to run the v2 sample tests on the v1 branches.
This PR instructs prow to not run tests on those branches.

ignore v2 sample tests on 1.x branches

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Cluster CIDR range is greater than maximum (25 > 21).
```
Signed-off-by: nareddyt <tejunareddy@gmail.com>

Fix ESPv2 cluster CIDR range

---

prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml

So that presubmit jobs changes in testgrid repo will be tested in the PR itself

Enable inrepoconfig for testgrid repo

---

prow/oss/cluster/kubernetes_external_secrets.yaml

This fixes #1666, which was an auto-generated PR from onboarding, which very likely was caused by a bug in the onboarding script, I will fix it separately

External secret for build-kpt-config-sync is in oss-prow project

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Add build cluster kubeconfig for kpt-config-sync

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Adds kubeflow pipelines sdk code style checks, including yapf, docformatter, and isort. These checks are initially set as optional=true and skip_report=true, then will be both be set to false (default) in a future PR once code is proven to be adherent and tests are consistently passing.

add kubeflow pipelines sdk code style checks

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Require KFP SDK code style checks after [kubeflow/pipelines/#8027](https://github.com/kubeflow/pipelines/pull/8027) makes code base adherent.

require KFP SDK code style checks

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Required formatting scripts are not ensured to exist on PRs into non-master base branches.
For example, this PR into base branch `sdk/release-1.8` has failures: https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/8112/kubeflow-pipelines-sdk-yapf/1556805615450329088

only run KFP SDK code style presubmits against master base branch

---

prow/oss/cluster/kubernetes_external_secrets.yaml
prow/oss/gencred-config/gencred-config.yaml

Generated by running this script: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/create-build-cluster.sh

Add external secret from build cluster for cloud-kubernetes-node-management-team

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Generated by running this script: https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/oss/create-build-cluster.sh
This is the second of 2 PRs, the 1st was: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1725

Add build cluster kubeconfig for cloud-kubernetes-node-management-team

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The large-job-pool on our prow build cluster uses c2-standard-30 nodes,
which come with 30 vCPUs and 120GB memory. These jobs request 29 vCPUs
and 40Gi memory, meaning each job can only run on a single node but
underutilizes the memory on that node. This increases the memory request
to improve memory utilization on the node. This will hopefully reduce
test flakiness.

increase CS e2e memory request to 80Gi

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

Currently cleanerupper is run hourly and cleans all of the resources the legacy periodic tests utilize including Guest Policy and OS Policy Assignments. Cleaning Guest Policy and OS Policy Assignments regularly pushes the cleanerupper job past its 30 minute limit due to sending a request to read policies in every zone offered in GCP, for OS Policy Assignments.
Guest Policy and OS Policy Assignments cleanup has been split in a separate job
* An hour limit has been configured to give the cleanerupper job ample time to finish.
* Frequency of this cleanup has been reduced to every five hours since I've noticed there's often [no policies to clean up](https://oss.gprow.dev/view/gs/oss-prow/logs/cleanerupper/1561776787086643200).

Reduce frequency of Guest Policy and OS Policy Assignments cleanup

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Trying to align with [this PR](https://github.com/kubeflow/pipelines/pull/8186)

Add in presubmit tests for kubeflow/pipelines for python v3.10

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The node pool can support running up to 10 concurrent jobs with the current resource requests. This bumps the max concurrency to improve cluster utilization and increase how many presubmits can run concurrently.

increase CS e2e max_concurrency to 5

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

While testing the parallel setting of the CS presubmit mono/multi jobs, the test pod got deleted due to memory pressure. 
This node used for the presubmit jobs has 112GiB memory. This PR increases the memory request from 80GiB to 105GiB to see whether it helps relieve the memory pressure.

Increase the memory request for e2e submit job

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The current configuration is leading to unschedulable pods. This reduces the resource requests in an attempt to ensure pods are schedulable on the e2e nodes.

reduce CS e2e resource requests

---

prow/oss/config.yaml

This will fix the Prow bump presubmit error

Fix skip_storage_path_validation error in presubmit

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The peak CPU usage of the presubmit mono/multi jobs is about 10 CPUs; The peak mem usage of the presubmit mono/multi jobs is about 16 GiBs.
This PR sets the CPU/mem requests to 17CPUs/30GiBs, so that we can support running three presubmit jobs on a single node concurrently.

Adjust the CPU/mem resources

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

This PR should be submitted before https://github.com/GoogleContainerTools/kpt-config-sync/pull/116.

Split the large presubmit job into multiple smaller ones

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

Currently, a PR triggers 3 mono presubmit jobs, and 3 multi presubmit jobs. Every mono/multi presubmit job requests about 50% of the CPU/mem resources of a node. So running mono/multi presubmit jobs for a PR requires 3 nodes. Our node pool currently has 12 nodes, and can support running presubmit jobs for 4 PRs at the same time.

Increase max_concurrency of mono/multi presubmit jobs from 3 to 4

---

prow/oss/plugins.yaml

- Add wip plugin to support draft/wip PRs
- Switch approve plugin to require_self_approval since most members of the team are approvers. This allows reviewers to differentiate between lgtm and approve.

update config sync plugins

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

there were breaking changes to the make targets and prow job specification since the 1.13 release branch. This creates separate jobs that can be run on the release branch for cherry picks.

add e2e jobs for v1.13

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

This service account is not used for presubmit jobs since the presubmits run in kind. The service account is for the periodic jobs which target GKE clusters.

remove prober-cred volume mount for presubmit jobs

---

prow/oss/plugins.yaml

The approve plugin by default links to go.k8s.io/bot-commands, which takes the user to https://prow.k8s.io/command-help rather then the oss prow deck. This updates the plugin configuration to direct the user to the command help page for oss.gprow.dev.

fix commandHelpLink for approve plugin

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/config.yaml

This was announced deprecated in March 2022, and officially deprecated since yesterday.

Gerrit repos defined globally instead of as command line args

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-utils.yaml
testgrid/config.yaml

It also moves the kpt-config-sync jobs to its own tab, which allows nested dashboard groups.

Add job spec for kpt-config-sync periodic jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

We're going to replace these two dummy test jobs with real CI jobs. Noop them in the interim.

Make the dummy test jobs always green

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
testgrid/config.yaml

The testgrid dashboard annotations are not added for the 6 new groups. We're planning to add them altogether.

Add the remaining 6 groups for kpt-config-sync multi-repo tests

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

It takes more time to run the config sync e2e tests on the autopilot clouster, so increasing it from 2h to 3h.

Increase the periodic job running time from 2h to 3h

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

the prow project has not yet been set up with all of the resources needed to run the tests

set GCP_PROJECT to stolos-dev in presubmits

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This change updates the job spec for one job to use workload identity. Only one job is changed so this can be tested without impacting the entire test grid.

experimental: use workload identity for periodic

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

the quotes were being expanded to the docker call, causing the execution to fail with invalid reference format error.

use empty string for PROBER_DOCKER_ARGS

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Tested workload identity on one job and it passed, so pushing the config to the rest of the jobs. If this is stable then the job that rotates the secret can be removed in a subsequent change.

switch periodic jobs to use workload identity

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

gke-test-infra needs extra permissions, staging k8s images are open

Update ESPv2 kubekins images to public URL

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The current machine type of the nodepool for config sync Kind prow jobs is n2-custom-32-65536, which has 32 vCPU and 64GB memory.
Requesting for 60GB for the docker container that runs the e2e test hits an insufficient memory issue. This commit decreases the memory request to 50GB.

Decrease the memory request for config sync Kind prow jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

Using the node pool label makes it difficult to recreate the node pool or incorporate more machine types into the node pool. This change uses a custom label selector to enable using multiple node pools for the kind presubmit jobs.

use custom labels for presubmit nodeSelector

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Signed-off-by: Wayne Zhang <qiwzhang@google.com>
To work around the deprecated log_dump script
https://github.com/kubernetes/kubernetes/tree/master/cluster/log-dump

set env USE_TEST_INFRA_LOG_DUMPING

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The config-sync multi-repo-test-group7 takes longer than 3h on autopilot clusters:
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-7-autopilot-stable/1584939438616612864.

Increase the periodic job timeout from 3h to 4h

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

Potential fix for https://oss.gprow.dev/view/gs/oss-prow/logs/post-oss-test-infra-deploy-prow/1585738959382646784
Job History: https://testgrid.k8s.io/googleoss-test-infra#prow-deploy

Update gcloud-in-go version to latest

---

prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

The old repository's image is no longer being updated.
issue https://github.com/GoogleCloudPlatform/oss-test-infra/issues/1818

Use k8s-staging-test-infra version of gcloud-in-go

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Given the recent release of Python 3.11, this PR tests the KFP SDK on Python 3.11.

test kfp sdk on python 3.11

---

prow/prowjobs/google/jwt_verify_lib/OWNERS
prow/prowjobs/google/jwt_verify_lib/jwt-verify-lib-presubmit.yaml
testgrid/config.yaml

Add configurations to use Prow as CI for https://github.com/google/jwt_verify_lib.
Changes added:
- Add a presubmit and a periodic job. This is re-using the docker container configured in other jobs managerd by our team ([GoogleCloudPlatform/esp-v2](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/GoogleCloudPlatform/esp-v2), [grpc-ecosystem/grpc-httpjson-transcoding](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding), [google/http_pattern_matcher](https://github.com/GoogleCloudPlatform/oss-test-infra/tree/master/prow/prowjobs/google/http_pattern_matcher)).
- Re-use the `esp-v2` Prow cluster that our team self-hosts on GCP.
- Create a new testgrid dashboard for this job.
Signed-off-by: …

Add Prow setup for jwt_verify_lib

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

With the monorepo code migrated to a separate repo, we no longer need to run the monorepo presubmits on kpt-config-sync. Note that with the reduction in prowjobs per presubmit we require fewer resources in a presubmit run. We could potentially increase the job concurrency accordingly, but for now I intend to scale down the node pool instead. We can scale the node pool back up later if we desire a higher job concurrency.

remove monorepo presubmits

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Multi repo mode is now the default, so this flag can be removed.

remove --multirepo flag

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This env var is no longer used and WI is supported by default

remove PROBER_DOCKER_ARGS

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The current periodics can take up to 4 hours to compelete which gets interrupted by the current 4 hour timeout. This change increases the timeout to reduce test flakiness.

chore: Increase timeout for kpt-config-sync autopilot periodics

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

TFX is not compatible with KFP SDK 2.0: https://github.com/tensorflow/tfx/blob/2450843564f4bc9297f01d1c8fd69c01c7dba4d8/tfx/dependencies.py#L133-L136
Installing KFP SDK from master head [[ref](https://github.com/kubeflow/pipelines/blob/4bb57e6723b7a5c2eb685536e5a293aea87bd3a1/test/presubmit-tests-tfx.sh#L33-L34)] only would be reverted later when installing tfx [[ref](https://github.com/kubeflow/pipelines/blob/4bb57e6723b7a5c2eb685536e5a293aea87bd3a1/test/presubmit-tests-tfx.sh#L48-L49)]. So we're not testing against master branch anyway.

Run `kubeflow-pipelines-tfx-python37` tests only on `sdk/release-1.8` branch.

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Latest envoy only builds with clang-14
Dockerfile changes in https://github.com/GoogleCloudPlatform/esp-v2/pull/755

[ESPv2] Update prow env to image with LLVM 14

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Mistakenly introduced in #1687 but not yet released for EL9. Will restore when ready.

no el9 for ar-plugin

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
testgrid/config.yaml

This is a similar set of periodic jobs that we run on the main branch. This set of periodics is intended to verify the current/latest release branch.

add Config Sync release periodics

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml

The kind jobs run directly in the build cluster rather than in a GKE cluster in the target project. There is currently a permission issue reading from GCR in the other project, so this pulls the image from the build cluster project instead.

use e2e-prow image from build cluster project

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml

NOTE: this change is to be reverted.
The CI for this specific has been failing with inconsistent failures, with some of them being 4h timeouts.
Extending the timeout temporarily to 5h to see if there could be a successful run. In the long term we should optimize the test to take less time.

Extend 7-autopilot-rapid-latest timeout to 5h

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

When disk_export.wf.json is modified, this presubmit should run to ensure that sbom generation still works. The presubmit should take around 7 minutes to complete.

Add sbom presubmit for disk export workflow modification

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml

Config Sync test group 7 includes testcases that switch source configs, which triggers the reconciler Pod to restart. It takes much longer time to restart a Pod on an autopilot cluster. Hence, this commit increases the timeout from 4h to 5h.

Increase the timeout for release CI jobs on autopilot clusters

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Some test-group-4 CI jobs on the autopilot clusters are close to 4 hours, e.g.,
https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/multi-repo-4-autopilot-regular/1615720761786372096.
The job will fail if it runs over 4h. This commit increases the time out for test-group-4 on autopilot clusters from 4h to 5h.

Increase the timeout for config sync test-group 4 CI jobs on autopilot clusters

---

prow/prowjobs/linux-review.googlesource.com/linux/kernel/git/torvalds/linux.yaml

This is currently triggering automatically _way_ too often, so hopefully this will fix that.
Instead, manually trigger kunit tests by commenting "run kunit tests".
Note that this affects the linux-review repository (with its branch pulled in from torvalds), not the kunit-review repository, which sees less use (and less spam).

kunit: Require manual trigger of the kunit presubmit

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

This uses an upgraded kubekins-e2e base image which contains Go 1.19.
Uses the image defined in https://github.com/GoogleContainerTools/kpt-config-sync/pull/466

ci: bump kubekins-e2e image

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

To fix test failure on `sdk/release-1.8` PR: https://github.com/kubeflow/pipelines/pull/9060#issuecomment-1489238473

run python 3.11 tests only on `master` branch

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Some modules used by KFP requires golang 1.20:
```
../../../../pkg/mod/k8s.io/kube-openapi@v0.0.0-20230501164219-8b0f38b5fd1f/pkg/cached/cache.go:242:16: undefined: atomic.Pointer
note: module requires Go 1.19
../../../../pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/synctrack/lazy.go:29:15: undefined: atomic.Pointer
note: module requires Go 1.20
FAIL	github.com/kubeflow/pipelines/backend/src/agent/persistence/worker [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/archive [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/auth [build failed]
FAIL	github.com/kubeflow/pipelines/backend/src/apiserver/client [build failed]
```

chore: Update golang used in kubeflow-pipelines-presubmits.yaml

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml

This postsubmit job publishes build artifacts on each submit event, including docker images, deployment manifests, and the nomos cli.
These are intended to be used by both users and by periodic CI jobs.

add kpt-config-sync postsubmit job

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This job checks the container analysis results in GCP for vulnerabilities on the postsubmit artifacts for the checked out commit.

add vulnerability scanning periodic job

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This job is relatively lightweight, so we can afford to run it more frequently. This will enable faster feedback on changes/fixes.

increase frequency of vuln scan job

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

Now that the sbom util path for linux image sbom generation is enabled, use that path for the presubmit instead of the syft-source path.

Use sbom util instead of syft source for presubmit

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

These targets use the newly added entrypoints for running tests in parallel on GKE. For now these jobs are experimental to discover any issues with the configuration, but the intention is to replace the testgroup-based jobs with this new pattern.

add config sync periodics for parallel gke

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Autopilot clusters require a region rather than a zone

fix: use region for autopilot clusters

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Only one of GCP_ZONE or GCP_REGION can be specified for creating a cluster. The makefile by default supplies a GCP_ZONE and must be unset.

explicitly unset GCP_ZONE for autopilot

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This updates the CI jobs to use create-clusters=lazy and destroy-clusters=false. This means the job will create the named clusters if they do not exist, and then leave them for the next execution to reuse.

update experimental e2e jobs to use lazy create

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The new job types run faster than the old ones, the e2e tests on standard now can often complete in ~45 minutes. Decreasing the interval will improve the turnaround time on the new periodics.

increase interval for new cs e2e jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This expands the new job type to the rapid channel on standard GKE. This also experiments with a new cluster shape which uses faster compute/storage but fewer overall resources.

add standard-rapid CS periodic using new job type

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Current image (gcr.io/cloudesf-testing/gcpproxy-prow:v20230705-1b3141e0-master) is causing ESPv2 presubmits to fail. Fixed image by including necessary llvm package - https://github.com/GoogleCloudPlatform/esp-v2/pull/834.
Test image:
```sh
IMAGE=gcr.io/cloudesf-testing/gcpproxy-prow:v20230705-1b3141e0-master
docker pull $IMAGE
docker run -i -t --entrypoint /bin/bash $IMAGE
git clone https://github.com/GoogleCloudPlatform/esp-v2.git && cd esp-v2 && mkdir bin
make build-envoy # This should FAIL
IMAGE=gcr.io/cloudesf-testing/gcpproxy-prow:v20230707-dad74d80-master
docker pull $IMAGE
docker run -i -t --entrypoint /bin/bash $IMAGE
git clone https://github.com/GoogleCloudPlatform/esp-v2.git && cd esp-v2 && mkdir bin
make build-envoy # This should PASS
```

Update gcpproxy-prow image to include llvm compiler-rt

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
testgrid/config.yaml

This is the intended dashboard format, where the periodics against the main branch will be consolidated into a single dashboard. The legacy testgroup based prowjobs and associated dashboards will be cleaned up once all of the new jobs are set up.

move new CS periodics to main dashboard

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Experimentally this shape is stable and the fastest of the configurations that were tested. It also consumes a lower overall resource footprint compared to the other configurations that were tested.

set cluster shape for new jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This implements all existing periodics using the new prow job type. Once these are all running and stable, we will begin retiring the old jobs.

add remaining CS prowjobs using new job type

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

https://github.com/GoogleCloudPlatform/oss-test-infra/pull/1987 unintentionally downgraded Go back to 1.18. This PR builds gcpproxy-prow image at https://github.com/GoogleCloudPlatform/esp-v2/pull/831. 
Build instructions:
```sh
git clone git@github.com:GoogleCloudPlatform/esp-v2.git && cd esp-v2
make docker.build-prow
make docker.push-prow
```
Testing instructions:
```sh
docker run -it --entrypoint /bin/bash gcr.io/cloudesf-testing/gcpproxy-prow:v20230712-v2.44.0-17-g94471d2e-master
go version
git clone https://github.com/GoogleCloudPlatform/esp-v2.git && cd esp-v2 && mkdir bin
make build-envoy
```

Update gcpproxy-prow image with Go1.20.5

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The image has been redefined for the new test-infra registry, but is essentially the same image.

chore: bump CS kubekins-e2e image

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

If the command is set to "/daisy", the shell variable within $(command) is not run. 
The command needs to be set to sh to get the gcloud secret successfully.

load shell variable before daisy command for presubmit

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

sh was discovered, however it seems that the command tried to directly run a file with shell.
We want to run daisy separately, after defining a variable which is the output of a gcloud command.

Separate parts of cmd for shell parsing

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

sh seems to interpret the first argument as a file, even if we are just trying to run the command.
Use /bin/bash instead

Use bash instead of sh

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

Explicitly run bash as a command, so the first argument isn't interpreted as a filename

Run bash as a command

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-image-tools.yaml

Following the template for the disk_export presubmit, use secrets for the windows presubmit.

Use secrets for windows sbom presubmit

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This is to pick up the change in
https://github.com/GoogleContainerTools/kpt-config-sync/pull/753/files.
A new docker image was pushed with the command:
`make build-vulnerability-scanner && make push-vulnerability-scanner`

Update the vulnerability-scanner image

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The stress tests manage and then delete a large number of resources. The reset code currently times out with the given cluster shape. Increasing the number of nodes enables the stress test to complete within the default timeout (experimentally).

increase cluster size for stress tests

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

It also changes the stress test to run on the Standard rapid-latest channel instead of the regular channel to match the Autopilot one.
We choose the rapid-latest channel because we observed that the latest GKE version often time consumes more resources, so we use that to detect stress test failures.

Add a CI job for ConfigSync stress test on Autopilot rapid-latest

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
testgrid/config.yaml

This uses the updated job shape which utilizes multiple clusters from a
single prowjob.
The release branch doesn't exist yet, so this pins to the latest RC tag on the main branch.
Note this is based on https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2035

add release branch CI for v1.16

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml

The job was pinned to a tag because the release branch was not yet ready when we wanted to update the job definitions. Under normal circumstances we will upgrade from branch->branch once the new release branch is ready.

bump release CI from pinned tag to branch

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml

Please submit this change after the previous PR was submitted and postsubmit job succeeded. Prow oncall: please don't submit this change until the secret is created successfully, which will be indicated by prow alerts in 2 minutes after the postsubmit job.
IIUC, pls wait for https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2050 to be merged and then approve/merge this PR.
Thanks
P.S.: More background copied from the other PR is reproduced below:
More details (internal references) on this:
* YAQS:  https://yaqs.corp.google.com/eng/q/144582480517660672?ved=0CAAQ0qAKahcKEwiY97rp_YSBAxUAAAAAHQAAAAAQHA
* TDD: [go/bmx-ci:pr-triggered-test-automation](http://go/bmx-ci:pr-triggered-test-automation)
* The full run of `create-build-cluster.sh` is at …

Add build cluster kubeconfig for bms-oracle-team

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/kubernetes_external_secrets.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/gencred-config/gencred-config.yaml

Reverting changes to recreate cluster due to incorrect service account while onboarding via:
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2050
* https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2051

Revert incorrect onboarding in PRs 2051 and 2050

---

prow/Makefile.gcloud.mk
prow/oss/Makefile
prow/oss/cluster/kubeconfigs/kubeconfigs.yaml
prow/oss/cluster/prow-controller-manager.yaml

The update to the kubeconfigs.yaml file has already been applied to the oss-prow cluster, and is a NOP.
/cc @michelle192837 @cjwagner @airbornepony @timwangmusic

fix kubeconfig for test-infra-trusted cluster

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/sinker.yaml

We've already tested that the settings in
https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2065 work for prow-controller-manager.
Mount the kubeconfig into crier, deck, deck-blueprints (for consistency with deck), hook, and sinker.
/cc @michelle192837 @cjwagner @airbornepony @timwangmusic

mount kubeconfigs configmap into other prow components

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The kpt-config-sync project uses go version 1.20, so this commit updates
the kubekins-e2e and gke-e2e image to ensure it is compatible with the go
version.
The gke-e2e image was built based on the commit in kpt-config-sync:
https://github.com/GoogleContainerTools/kpt-config-sync/commit/f11bb971f413a6c9ee0e11378568b841c717b23e.

Update the kubekins-e2e and gke-e2e image for kpt-config-sync

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Latest run is timing out: https://oss.gprow.dev/view/gs/oss-prow/logs/cit-periodics-performance/1704783248854355968

Bump cit-performance-peridiocs timeout to 5h to accomodate windows images

---

.prow/presubmits.yaml
prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/sub.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml

I think one of the changes in this release is interfering with presubmit triggering for inrepoconfig. Reverting.

Revert "Update oss-prow to v20230927-f8b8856dbc"

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

[Testgrid](https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics) is stale because everything is timing out from the new images. Not sure if 3hrs is enough, we'll see.

Change CIT 2hr peridiocs to 3hr with same timeout

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

This reverts commit c2c576001dab27cb85fead6c459ceda323c6318e.
Turn out the change doesn't work and I just found we can still have [workaround](https://github.com/envoyproxy/envoy/issues/28670#issuecomment-1699092290) for building as root.

Revert "Update prow image to oct 12"

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

Use the go-canary image variant, because it includes Go 1.21, which is required to run `go mod tidy` in presubmits, after we upgrade to Go 1.21, which is required in order to upgrade kpt. Previously we pinned to the 1.26 variant, to ensure a specific version of k8s was used. The go-canary variant is pinned to the `stable` version of k8s, which today is v1.28.2 (per https://cdn.dl.k8s.io/release/stable.txt).

Update kpt-config-sync presubmit image

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml

Presumbists worked with this new image. So this updates the rest of the periodics and postsubmits.

Update kpt-config-sync test images

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The autopilot stress tests sometimes take longer than 2 hours when running on a single cluster, causing them to timeout. This change adds another cluster to shorten the runtime.

use 2 cluster for autopilot stress tests

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

We are missing a lot of gobuild/gocheck/gotest coverage because these containers are scoped to only subdirectories which belong to the same module as the main directory. This change will add each module as its own presubmit directory to ensure coverage.
citpresubmit still handles building and testing because of the way we handle test code in those directories.

Revamp guest-test-infra presubmit checks

---

prow/oss/plugins.yaml

With the new request to require the Github UI approval button on our
repository, we've lost the ability to effectively approve a PR
without granting lgtm. Disabling review_acts_as_lgtm will enable an
approver to grant the approval state/label without granting lgtm.
Context:
https://github.com/GoogleContainerTools/kpt-config-sync/issues/1002 Requested for us to require the Approval UI button, despite our usage of prow to manage lgtm/approval. There is a bit of redundancy now with the approval mechanisms, but this should allow us to separate approve from lgtm again.

disable review_acts_as_lgtm for kpt-config-sync

---

prow/oss/cluster/kes-kicker.yaml

The problem with kubernetes-external-secrets (KES) is that it can start failing, but where the process does not exit. So from Kubernetes' point of view, it doesn't know that it should restart KES.
Inform our Prow instance that we want to restart KES regularly, with a CronJob. This has the advantage that it will continue to run even if there are any issues with Prow itself.
Tested locally against my local Prow instance.
/cc @cjwagner @airbornepony @timwangmusic

add manual k8s CronJob to regularly restart KES

---

prow/oss/cluster/kes-kicker.yaml

In #2125, we created various resources (ServiceAccount, Role,
RoleBinding, CronJob) all with the name "kes-kicker". Looking at the
cluster after these configurations have been applied, they all appear to
be in the "test-pods" namespace.
Consequently, we get an error like this in the logs from the kes-kicker
pod when it gets scheduled to satisfy the CronJob definition:
Error from server (NotFound): deployments.apps "kubernetes-external-secrets" not found
This appears to be because the kubectl command inside kes-kicker is
operating inside the test-pods namespace.
Recreate the same resources in the default namespace. But also, give the
kubectl invocation an namespace because it's more strict that way and it
can't hurt.
/cc @cjwagner @airbornepony @timwangmusic

kes-kicker: target 'default' namespace

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The primary motivation of this change is to upgrade to a newer version that has Go 1.21.

chore: bump gke-e2e image used by config sync e2e

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Adds execution tests for KFP's Kubernetes-specific features provided by `kfp-kubernetes`.

add `kfp-kubernetes` execution tests

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Tests are implemented and [passing](https://github.com/kubeflow/pipelines/pull/10304) (see [logs](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/kubeflow_pipelines/10304/kfp-kubernetes-execution-tests/1735056424230195200)).

make `kfp-kubernetes` execution tests required

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Tests were passing, but are now failing. Pipelines are stuck in a "Running" state, despite inner tasks all succeeding.
/assign @chensun

Revert "make `kfp-kubernetes` execution tests required"

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

/cc @elicriffield @zmarano 
the cit gobuild config already does this

build & test root, registry image, cleanerupper, and cit whenever go.mod or go.sum is changed

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

This is because all the integration tests have been removed due to them being broken.

Remove go-integ presubmit for Guest Agent

---

prow/oss/plugins.yaml

The /close command is notably missing!

k8s-config-connector: enable lifecycle commands

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This adds the new helm/oci provider flags for the periodic job configs. This sets the GKE tests to run with the artifact registry provider and the kind tests to run with the local provider.

ci: add helm/oci provider options for CS e2e

---

prow/prowjobs/GoogleCloudPlatform/compute-image-import/compute-image-import.yaml

Migrating the test containers of Image Import from "gcp-guest" to "compute-image-import".

Migrating Image Import Containers for all tests

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

We are running into some quota issues with the number of concurrent tests running at once. This change reduces the test frequency to every two hours, and staggers the execution such that the standard jobs run on even hours and the autopilot jobs run on odd hours.

ci: stagger execution of CS periodics

---

prow/oss/plugins.yaml

My understanding is that requiring self approval will make it such that PRs opened by OWNERS don't get the `approved` label.

k8s-config-connector: require self approval

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics-performance
Test times out due to adding more images, prow kills the CIT job, killing the job stops it from cleaning up resources, then new jobs either timeout in prow or timeout waiting for quota because the zombie resources are taking it all.
We need to both bump the timeout for this job, and clean up zombie resources. This PR will do the first, I'll do the second thing manually.
I don't think increasing job count will help since we're bumping up against the limits of our quota with 10 jobs.
/cc @koln67 @zmarano

Bump timeout for cit-periodics-performance

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Still seeing some timeouts of individual workflows getting stuck. The fill disks step is adding a lot of runtime, going to bump timeout to 60m.
/cc @koln67 @zmarano

Bump individual workflow timeout to 60m for cit-periodics-performance

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This change gives a minute offset to each of the big jobs to further stagger them. This is primarily motivated by the autopilot jobs so that not all clusters are scaling from zero at the same time.

ci: further stagger each large GKE job

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Use fewer larger nodes, to give the reconcilers more headroom to run faster, even with low resource requests.

configsync: increase stress test node size

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

https://testgrid.k8s.io/q/config/googleoss-gcp-guest/cit-periodics not really using buganizer components
/cc @zmarano @elicriffield

Switch to alerting via email

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

I misunderstood the threshold definition and have to use the deprecated debug-url field.

Fix issues with cit alerting configuration

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Also disable setting exit status to avoid always marking the job failed.

Only configure alerting thresholds on prow annotations

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The kind test covers testing with the local test-git-server. This commit
changes other CI jobs to test with the Cloud Source Repository so that
we don't need a separate job for Git + WI tests.
It also removes the test regex for those one-off jobs because
https://github.com/GoogleContainerTools/kpt-config-sync/pull/1160
changes the e2e test to run these tests if and only if the flag is
specified.
b/325119647

Change the default Git provider to CSR

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Moving all alerting configuration to the k8s testgrid repo, and removing `set_exit_status false` option (I think I can make broken_column_threshold work this time.
/hold

Update CIT alerting config

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

This should help with quota issues and be a more efficient use of resources. The images in cit-performance-periodics change very infrequently so the weekly interval should be fine for testing. The images in ubuntu-daily-cit-performance change more frequently so I lowered to half a week. I have more detailed math if you want to check yourself but based on historical data I'm expecting runtimes of 8.4 - 19.7 hours (with an average of 11.4 hours), which gives a four hour buffer before timeouts. parallel_count=1 is more efficient but doubles these runtimes and running a prow job for longer than 24 hours requires some extra configuration beyond just time IIUC so I've stuck with this for now.
/cc @bkatyl @elicriffield

Run performance periodics on a longer, lower interval

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

Most Config Sync CI uses Cloud Source Repository as the Git provider to run the e2e tests. We're currently hitting the write limit, and it requires updating the project portfolio to increase the quota.
```
ERROR: (gcloud.source.repos.create) ResponseError: status=[RESOURCE_EXHAUSTED], code=[429], message=[RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'Number of write requests' and limit 'Number of write requests per minute' of service 'sourcerepo.googleapis.com' for consumer 'project_number:770236578952'.]
```
CI link: https://oss.gprow.dev/view/gs/oss-prow-build-kpt-config-sync/logs/kpt-config-sync-standard-rapid-latest/1773451412810764288
This commit decreases parallism by reducing the number of E2E test clusters, so there would be fewer concurrent write requests to CSR.
Another …

Tune E2E_NUM_CLUSTERS for kpt-config-sync CI to decrease parallism

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

My math was slightly off, last run timed out with 13 networkperf runs left to finish. For now I want to keep execution under 24hrs, to keep prow configuration simple. Bumping parallel count by 1 should easily get it there.
/cc @zmarano @elicriffield

Bump cit-performance-peridiocs parallel count

---

prow/oss/Makefile

Defaulted to test-pods, which is incorrect for the rule.

Specify namespace in update kubeconfig target

---

prow/oss/cluster/prow-controller-manager.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

This should have triggered a deployment, but didn't: https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2236

Make postsubmit deploy job run on Makefile changes.

---

prow/oss/oss-autobump-config.yaml

To address this error: https://oss.gprow.dev/view/gs/oss-prow/logs/ci-oss-test-infra-autobump-prow-for-auto-deploy/1778166330562711552

Add autobump consistency exceptions for non-prow container images.

---

prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml

* change command to `make all` which covers build, running test and coverage.
* remove rgraph unstable branch from prow - this branch is deprecated

Change prow command for k8s-cloud-providers

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Mitigating: https://github.com/kubeflow/pipelines/issues/10779

Temporarily make KFP e2e test and upgrade test non-blocking

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

To the latest version: gcr.io/cloudesf-testing/gcpproxy-prow:v20240503-v2.46.0-17-ge72b17e9-master

Update ESPv2 prow image

---

prow/oss/plugins.yaml

As discussed in https://github.com/kubeflow/kubeflow/issues/7549#issuecomment-2091871635, and other places.
We need to ensure that approvers are explicitly approving their PRs in the Kubeflow org, as this prevents people from accidentally merging PRs with a single `/lgtm`.
This PR updates the prow configs so that all currently active Kubeflow repos require people who are approvers to explicitly `/approve` their own PRs, if that is their intention.
__NOTE:__ it might be possible to just enable this at the org level by including `kubeflow` as a list element, but I am not super familiar with how the config works.

Require self-approval for Kubeflow repos

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

With the number of concurrent jobs we have running against a single project, we were frequently hitting the CSR api quota. This switches back to the local git provider as the default and creates a separate job for testing CSR.

ci: use local git provider as default for CS jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The current Autopilot jobs failed due to Cilium API client timeout error.
The GKE team has marked a few versions as bad. This commit pins to a specific working version for the rapid and rapid-latest CIs. The regular channel doesn't have the fix available yet. It may take another 1-2 weeks until the fix is available in the regular channel. The stable channel seems to be okay with an older version.
b/339056595

Pin to a specific cluster version for Autopilot rapid and rapid-latest

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-periodics.yaml
prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

- Python 3.7 is in EOL, so bump containers used in KFP CI to python 3.8 for now
- Additionally, the KFP SDK no longer supports python3.7 so tests using these images are broken

chore: Bump python version for Kubeflow Pipelines CI

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

This has been timing out since we added 24.10 I believe. Individual images are still completing in a reasonable time.
/cc @zmarano @elicriffield

Bump ubuntu daily shapevalidation periodic timeout

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit backend tests to a GHA: https://github.com/kubeflow/pipelines/pull/10871
This PR removes presubmit backend tests from the prow config in parallel.

chore: Remove KFP presubmit backend test prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of the migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit e2e tests to a GHA: https://github.com/kubeflow/pipelines/pull/10887
This PR removes presubmit e2e tests from the prow config in parallel.

chore: Remove KFP presubmit kubeflow-pipeline-e2e-test test prow config

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Older images are either not UEFI or getting obsoleted/deleted and/or have bad versions of the agents that can't run the CIt test. Switching to new custom, family-less immages that will consistently pass.

Switch older CIT test images to known good ones

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit frontend tests to a GHA: https://github.com/kubeflow/pipelines/pull/10923
This PR removes presubmit frontend tests from the prow config in parallel.

chore: Remove KFP presubmit frontend test prow config

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The primary change is the upgrade to Go 1.22

chore: bump config-sync gke-e2e image

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

chore: bump Config Sync presubmit images

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

The multi-repo aliases reflect a legacy naming scheme, and all current branches support the new name.

chore: use renamed config-sync test targets

---

prow/oss/config.yaml

This fixes an issue where the dind container is on a host with a MTU lower than the typical default of 1500, resulting in a mismatch.
Upstream maintainers are considering making this the default behavior of the script, but for now this is a quick workaround.
See: https://github.com/kubernetes/test-infra/blob/94f76aedb29b50131fe5dc5e131adcd23f6d4f22/images/bootstrap/runner.sh#L87

enable MTU workaround for dind presets

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-terraform.yaml

This is more flexible than the strict gke node pool selector, allowing the underlying node pools to be changed without downtime and/or coordinating changes to the prow config. Also separates presubmits from periodic nodes for better isolation/security.

add node label selectors to all CS jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The kind periodic config has drifted a bit from the presubmit config. Updating them to be in sync again.

chore: sync kind periodics with presubmits

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP presubmit SDK Execution test to a GHA: https://github.com/kubeflow/pipelines/pull/10975
This PR removes presubmit SDK Execution test from the prow config in parallel.

chore: Remove KFP presubmit SDK Execution test prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-postsubmits.yaml
prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As discussed in https://docs.google.com/document/d/1cHAdK1FoGEbuQ-Rl6adBDL5W2YpDiUbnMLIwmoXBoAU/edit?disco=AAABPj_J-a4, removed:
- kubeflow-pipeline-mkp-test
- kubeflow-pipeline-mkp-snapshot-test
- kubeflow-pipeline-postsubmit-mkp-e2e-test
PR to remove the tests from the kubeflow/pipelines repo:
- https://github.com/kubeflow/pipelines/pull/10924
/assign @chensun

Removed mkp tests

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of the migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit kfp-kubernetes-execution-tests to a GHA:
- https://github.com/kubeflow/pipelines/pull/10926
This PR removes presubmit kfp-kubernetes-execution-tests from the prow config in parallel.
/assign @chensun

chore: Remove KFP presubmit kfp-kubernetes-execution-tests tests prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP presubmit SDK YAPF test to a GHA: https://github.com/kubeflow/pipelines/pull/10961
This PR removes presubmit SDK YAPF test from the prow config in parallel.

chore: Remove KFP presubmit SDK YAPF test prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of the migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migratekubeflow-pipelines-backend-visualization tests to a GHA: https://github.com/kubeflow/pipelines/pull/10984
This PR removes presubmit kubeflow-pipelines-backend-visualization tests from the prow config in parallel.
cc @chensun @zijianjoy

Removed kubeflow-pipelines-backend-visualization

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP presubmit SDK Runtime tests to a GHA: https://github.com/kubeflow/pipelines/pull/10991
This PR removes presubmit SDK Runtime tests from the prow config in parallel.

chore: Remove KFP presubmit SDK Runtime tests prow config

---

prow/oss/config.yaml
prow/oss/plugins.yaml
prow/prowjobs/GoogleCloudPlatform/gke-networking-api/OWNERS
prow/prowjobs/GoogleCloudPlatform/gke-networking-api/gke-networking-api-config.yaml

GKE Networking CRDs were moved to a new repo
GoogleCloudPlatform/gke-networking-api from
kubernetes/cloud-provider-gcp.
See this PR https://github.com/kubernetes/cloud-provider-gcp/pull/725 for additional details.
This CL adds a prowjob to run the verification script for the gke-networking-api repo.

Add a prowjob for gke-networking-api.

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP presubmit SDK Upgrade test to a GHA: https://github.com/kubeflow/pipelines/pull/10989
This PR removes presubmit SDK Upgrade test from the prow config in parallel.

chore: Remove KFP presubmit SDK Upgrade test prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate KFP SDK misc tests to a GHA: https://github.com/kubeflow/pipelines/pull/11032 
This PR removes presubmit SDK tests from the prow config in parallel.

chore: Remove KFP presubmit SDK misc tests prow config

---

prow/prowjobs/GoogleCloudPlatform/esp-v2/esp-v2.yaml

Update the gcpprow-proxy to the latest image built with go version set to 1.22.5

Update gcpproxy-prow to latest image

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of the migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit `kubeflow-pipelines-samples-v2` test to a GHA: https://github.com/kubeflow/pipelines/pull/11048
This PR removes presubmit `kubeflow-pipelines-samples-v2` from the prow config in parallel.
cc @chensun

chore: Remove KFP presubmit kubeflow-pipelines-samples-v2 test prow config

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Removing kubeflow-pipeline-upgrade-test due to https://github.com/kubeflow/pipelines/pull/10932.
cc @chensun

Removed kubeflow-pipeline-upgrade-test from Kubeflow Pipelines tests

---

prow/prowjobs/GoogleCloudPlatform/gke-networking-api/gke-networking-api-config.yaml

The current image is using go1.20 and throwing errors on go.mod with newer go versions:
https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/GoogleCloudPlatform_gke-networking-api/17/pull-gke-networking-api-test/1820882218180939776

bump test image for gke-networking-api

---

.prow/presubmits.yaml
prow/bump.sh
prow/oss/README.md
prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/gerrit.yaml
prow/oss/cluster/ghproxy.yaml
prow/oss/cluster/grandmatriarch_default.yaml
prow/oss/cluster/grandmatriarch_test-pods.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/horologium.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/cluster/sub.yaml
prow/oss/cluster/tide.yaml
prow/oss/config.yaml
prow/oss/oss-autobump-config.yaml
prow/prowjobs/GoogleCloudPlatform/blueprints/GoogleCloudPlatform_blueprints_checkconfig.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml
prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml
prow/tests/jobs_test.go

This includes three changes:
- Upstream misc test-infra images are now published to gcr.io/k8s-staging-test-infra, so update image references to use that. gcr.io/k8s-prow > gcr.io/k8s-staging-test-infra
- Upstream Prow images use the gob-prow AR images that are maintained by the Prow dev team (and are separate from the ones published in k8s-sigs/prow). gcr.io/k8s-prow > us-central1-docker.pkg.dev/gob-prow/prow-images
- Autobump config needs to use the new locations, and has a split now to update the two different locations (for Prow and misc images). Prow images remain consistent, misc images don't have to.
Images in gcr.io/k8s-staging-test-infra are public, but this requires that oss-prow has permissions to pull images from us-central1-docker.pkg.dev/gob-prow/prow-images. (I've granted …

Update image locations to use new locations.

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

As part of the migration from Prow to GH Action Workflows for KFP, we have a PR proposed to migrate presubmit kubeflow-pipelines-manifests tests to a GHA:
- https://github.com/kubeflow/pipelines/pull/11066
This PR removes presubmit kubeflow-pipelines-manifests from the prow config in parallel.

chore: Remove KFP presubmit kubeflow-pipelines-manifests tests prow config

---

prow/prowjobs/GoogleCloudPlatform/k8s-cloud-provider/k8s-cloud-provider-config.yaml

We want to use a new version of Go in https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/217

Update kubekins-e2e image

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The githubapp tests are currently implemented as a one off test suite similar to kcc and gcenode. This creates a separate prowjob which runs only the new githubapp tests.
Depends on https://github.com/GoogleContainerTools/kpt-config-sync/pull/1372

ci: add prowjob for Config Sync githubapp

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

AR has a fixed quota of 30 repo create/delete requests per minute, which is occasionally being exhausted in the current configuration. This switches the gitprovider job types to use local helm/oci provider so that they do not create AR repos, given that standard-regular already has test coverage for AR.
Also sets the cron schedule for standard/autopilot regular to be on the same even/odd hour schedule as the other standard/autopilot jobs.

minimize concurrent AR repo creates/deletes

---

prow/oss/oss-autobump-config.yaml

The job needs permissions to read from the source project (gob-prow), but doesn't have them. Update autobump to use application default credentials (via `imageRegistryAuth: google`) to fix this, similar to the gob-prow autobump job.
Tested locally that this should be sufficient (assuming permissions are granted in gob-prow correctly).

Use default application credentials with autobump

---

prow/prowjobs/grpc-ecosystem/grpc-httpjson-transcoding/transcoding.yaml

v20240727-v2.46.0-27-g6c21f955-master is the one used by ESPv2. I've tested in the grpc-httpjson-transcoding repo.

Change grpc-httpjson-transcoding prow image to be same as ESPv2

---

prow/oss/cluster/crier-kicker.yaml
prow/oss/cluster/deck-kicker.yaml
prow/oss/cluster/prow-controller-manager-kicker.yaml
prow/oss/cluster/sinker-kicker.yaml

This resolves an issue where components cannot perform their tasks on cluster with legacy auth due to expired credentials, resulting in authentication / authorization issues. For example, we were seeing pod creation issues from the prow-controller-manager.

Add cron jobs to restart pcm/crier/sinker/deck every day

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

There is an issue with the cluster autoscaler which is currently undergoing a RCA. Changing the cluster names will allow new clusters to be created and for the tests to pass in the meantime.

create new clusters for autopilot-rapid tests

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

remove all-gcpc-modules-test prow config as it's being migrated to GHA.  [kubeflow/piplelines/11157](https://github.com/kubeflow/pipelines/pull/11157) 
Relates to:   [kubeflow/piplelines/11154](https://github.com/kubeflow/pipelines/pull/11154)

chore: remove all-gcpc-modules-test prow config as it's being migrated to GHA

---

prow/prowjobs/kubeflow/pipelines/kubeflow-pipelines-presubmits.yaml

Removed in favor of https://github.com/kubeflow/pipelines/pull/11125

Remove kubeflow-pipelines-integration-v2 from Prow Config

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

It appears that new versions of autopilot (currently only in rapid channel) scale up slower, and as a result the tests are occasionally timing out. The average runtime is very close to the current 2h timeout, causing it to sometimes pass and sometimes time out.
A 4h timeout matches the current timeout set on the prow job config.

bump timeout for config sync autopilot tests

---

prow/prowjobs/GoogleCloudPlatform/testgrid/testgrid-jobs.yaml

We switched from a master branch to a main branch a while back in the GCP/testgrid repo, but apparently neglected to update the related jobs. (I suspect this got missed during the branch change due to other priorities / team changes around that time).
Jobs may need fixes after this is submitted, but this should at least get them up and running again.

Trigger TestGrid jobs on main, not master, branch.

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

This reverts commit 8698884a1f6b4b89e05e439936dadd67e35350db.
Reason for revert: RCA is complete for these clusters, so the tests can switch back to the original cluster names.

Revert "create new clusters for autopilot-rapid tests"

---

prow/oss/cluster/sinker.yaml

I noticed that sinker can't connect to some build clusters, presumably due to switching auth for those clusters to rely on workload identity since sinker is missing that.
I've already granted `roles/iam.workloadIdentityUser` to `oss-prow.svc.id.goog[default/sinker]` so this should take affect after this PR merges and we restart sinker.
/assign @michelle192837

Bind sinker to the same GSA as prow-controller-manager.

---

prow/oss/misc-images-autobump-config.yaml
prow/oss/oss-prow-autobump-config.yaml
prow/prowjobs/GoogleCloudPlatform/oss-test-infra/gcp-oss-test-infra-config.yaml

I added autobumping for misc images when I updated the autobump job to reference the new Prow image location, but these should be split so the changes can be reviewed, submitted, monitored, and rolled-back separately.
Also updating the alert email, since OSS Prow alerts should go to us and not SIG K8s Infra folks. (Feel free to suggest a better one).

Split the OSS Prow and misc image autobumps.

---

prow/oss/misc-images-autobump-config.yaml

These image versions aren't expected to be consistent since they cover several miscellaneous images.
Fixing current failures like
https://oss.gprow.dev/view/gs/oss-prow/logs/ci-oss-test-infra-autobump-misc/1840851764627116032

Don't expect misc images to be bumped consistently.

---

prow/oss/config.yaml

The `regenerate-crds` job is only triggered on PRs created by dependabot. This prevents automatic merges for other PRs in the GoogleCloudPlatform/gke-networking-api repository. Marking the job as optional will allow automatic merges to proceed.

Mark optional jobs in gke-networking-api.

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml

google-guest-agent is wrapping the checks and builds into its own build system, instead of using the container provided build scripts with this change now it uses the in tree build system.

google-guest-agent: turn to using the build system

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml

Instead of passing the arguments into the command line provide it with its own key: args.

google-guest-agent: update the build call

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/google-guest-agent.yaml

As we support both linux and windows build we need to assert each PR builds and complies with golint + gofmt on windows  as well.

google-guest-agent: enable windows check and build

---

prow/oss/config.yaml

- This PR updates the Tide configuration for the Kubeflow/Pipelines repository to enforce the requirement of a ci-passed label before allowing pull requests to be merged. 
- This change ensures that only changes with successfully passing continuous integration checks can be merged.

Update Tide configuration to require ci-passed label for PR merges in Kubeflow repository

---

prow/oss/plugins.yaml

This PR enables the `/retitle` command on Kubeflow repos.
This PR makes it so that `/retest` will trigger GHA workflows on Kubeflow repos.

Enable retitle and GHA triggers on Kubeflow repos

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

We have limited capacity, we need to be more economical with how we use it. This is enough for a regression signal.
This should help our image builds find capacity more easily.
/cc @zmarano @lpleahy

Lower accelerator specific cit-peridiocs to once per day

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

The timezone for this is UTC so it needs to run at 0400 UTC to run at 8PM pacific.
/cc @zmarano @lpleahy

Fix accelerator cit-periodics cron

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The primary motivation is to pick up Go version 1.23

chore: bump gke-e2e version for config sync e2e

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

The reservation was deleted and recreated. guestos-a3u-gsc no longer exists
/hold
/cc @zmarano @jjerger

Update A3Ultra reservation name for accelerator periodics

---

prow/prowjobs/google/oracle-toolkit/OWNERS
prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

When run with ansible 2.11, tests are failing with the error
```
ERROR! couldn't resolve module/action 'mount'. This often indicates a
misspelling, missing collection, or incorrect module path.
The error appears to be in
'/home/prow/go/src/github.com/google/oracle-toolkit/roles/brute-ora-cleanup/tasks/main.yml':
line 231, column 3, but may be elsewhere in the file depending on the exact syntax problem.
```
Testing with 2.12 I see the same error, but in 2.9, the error goes away. So for now let's revert to 2.9 to unblock tests.
Successful output (internal):
https://paste.googleplex.com/4939247786917888?raw

Revert oracle-toolkit Ansible runner version

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Attempt to automatically run presubmits on new PRs;  will still require /ok-to-run for folks who don't already have repo permissions

Enable always-run oracle-toolkit-presubmit

---

prow/oss/plugins.yaml

Part of: https://github.com/kubeflow/training-operator/issues/2402
These changes are required to rename `kubeflow/training-operator` to `kubeflow/trainer`
cc @kubeflow/kubeflow-steering-committee @franciscojavierarceo @juliusvonkohout @kubeflow/wg-training-leads @Electronic-Waste @astefanutti @airbornepony @chases2 @cjwagner @michelle192837 @nathanperkins
/hold for review

Rename kubeflow/training-operator to kubeflow/trainer

---

prow/oss/create-build-cluster.sh

This doesn't automatically create a CL anymore, but we can iterate on that later if desired. Overall, this onboarding process is simpler.
cc @AlexBasinov 
/assign @simony-gke

Modernize create-build-cluster.sh to use gke-auth-plugin kubeconfigs rather than gencred+KES.

---

README.md
prow/oss/README.md
prow/oss/onboarding.md

I looked for any links to github.com/kubernetes/test-infra and replaced ones that were not permalinked with the updated URLs.
/assign @simony-gke

Fix broken links to old Prow source location.

---

prow/oss/create-build-cluster.sh

Oops, I forgot to retest after adding the `roles/container.developer` IAM grant.
I've fixed this bug and validated:
```
ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Policy members must be of the form "<type>:<value>".
- '@type': type.googleapis.com/google.rpc.BadRequest
fieldViolations:
- description: Policy members must be prefixed of the form '<type>:<value>', where
<type> is 'domain', 'group', 'serviceAccount', or 'user'.
field: policy.bindings.member
```
/assign @AlexBasinov @simony-gke

Fix create-build-cluster.sh Prow SA binding to test cluster.

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Previously the machine shape was hard coded into the test suite. We want to make it generic, so the first step is to pass in the machine shape argument.

Add the machine shape argument to accelerator tests

---

prow/oss/plugins.yaml

Currently in the Kubeflow org, we have issues with people LGTMing PRs that are in root approvers, causing the PR to merge immediately.
So we can separate the idea of LGTM and APPROVE, this PR makes it so that an LGTM does not also APPROVE.
It also makes it so that we don't have to explicitly list out our repos anymore, an just applies the configs to the whole `kubeflow` org.

Stop LGTM acting as approve in Kubeflow

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The stress tests need enough nodes to schedule 1,000 pods. The pods are small, but each node has a 110 pod limit. Control plane initial scale is dependent on number of vCPUs, so fewer cores per node should work with more nodes.
Since the stress tests extend the non-stress test template, I've hard coded the values in the stress config, so we can remove them from the non-stress test template later, and fall back to dynamic defaults in the test code.

kpt-config-sync: more nodes for stress tests

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

A3U and A4 have to be split due to the reservation requirement. Looking into if/when we can combine these by removing that need.

Add A4 to CIT accelerator periodics

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics-release.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-postsubmits.yaml
prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-presubmits.yaml

This bumps the kubekins-e2e image used by the Config Sync jobs to the current latest k8s 1.31 image.

chore: bump kubekins-e2e for Config Sync jobs

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

The stress tests don't have a memory limit, but they're often getting OOMKilled by the kernel during some of the more memory intensive tests. So increase the memory request to 20GiB to avoid node conjestion.

kpt-config-sync: increase stress test memory

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

TestStressManyDeployments needs at least 13x 4cpu  nodes to have enough cpu for 1k pods requesting 50m each.

kpt-config-sync: more stress test nodes

---

prow/oss/plugins.yaml

This PR updates the Kubeflow org config so using the GitHub review is treated as an LGTM / LGTM-cancel rather than an approve.
This is to avoid accidental merges by root approvers who use the GH review to say they have looked at it and are happy, and means that people now have to explicitly `/approve` to merge a PR.

Treat GH approve as LGTM for kubeflow org

---

prow/oss/plugins.yaml

This should allow `kubeflow-trainer-maintainers` GitHub team to apply milestones for the Kubeflow Trainer project.
We can create this team without `write` access to the repo, which will allow maintainers to use `/milestone` command.
Does it sound good to you @terrytangyuan @johnugeorge @Electronic-Waste @tenzen-y @rimolive @varodrig  @astefanutti?
/assign @airbornepony @chases2 @cjwagner @michelle192837 @nathanperkins

feat(kubeflow): Enable milestoneapplier plugin and milestone team

---

prow/oss/plugins.yaml

As we discussed in https://github.com/kubeflow/internal-acls/pull/766#discussion_r2046453042, we decided to rename `kubeflow-trainer-maintainers` to `kubeflow-trainer-team`.
/cc @terrytangyuan @johnugeorge @andreyvelich @tenzen-y @rimolive @varodrig @astefanutti
/assign @airbornepony @chases2 @cjwagner @michelle192837 @nathanperkins

fix(kubeflow): rename kubeflow-trainer-maintainers to kubeflow-trainer-team

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Set the serviceAccountName to prowjob-default-sa for presubmit tests to avoid using the Compute Engine default service account to follow recommended best practices.

Set custom service account for presubmit tests

---

prow/oss/cluster/crier.yaml
prow/oss/cluster/deck.yaml
prow/oss/cluster/deck_blueprints_deployment.yaml
prow/oss/cluster/hook.yaml
prow/oss/cluster/kubernetes_external_secrets.yaml
prow/oss/cluster/prow-controller-manager.yaml
prow/oss/cluster/sinker.yaml
prow/oss/config.yaml
prow/oss/gencred-config/gencred-config.yaml

In https://github.com/GoogleCloudPlatform/oss-test-infra/pull/2458, we registered a new build cluster to run presubmit jobs. However, these jobs are now failing with the following error:
"Terminal error: nonretryable error: no build client found for cluster
alias "build-gcp-oracle-team". If this was previously working, then it''s likely
that the credentials expired, there was a CA cert expiry, or we cannot reach your
cluster API for some other reason."
Failed prow job for reference: [Prow job link ](https://oss.gprow.dev/prowjob?prowjob=c4b45b30-4535-4b21-a924-dddba384ab01)
Based on an internal Q&A thread, filing this PR to remove the old cluster context from the legacy kubeconfig secret to address the issue.

Remove all references to the old build cluster

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Remove the `hostNetwork: true` parameter from the `ansible-runner` Pod spec in order to enable Workload Identity.
As per the [official documentation on Workload Identity restrictions](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity#restrictions):
> Caution: Pods running on the [host network](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hosts-namespaces) (hostNetwork: true) don't use Workload Identity Federation for GKE. GKE automatically routes requests from these Pods to the Compute Engine metadata server.
Internal bug: b/414410133

Enable Workload Identity for ansible-runner Pod

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

This PR introduces a new test case for single-instance Oracle setup on a Bare Metal Solution machine. To support this, the existing toolkit runner shell script has been split into two distinct scripts: 
presubmit_tests/single-instance-on-bms.sh for this new test case and presubmit_tests/rac-on-bms.sh for RAC.
Note: These script filenames will be updated in a subsequent PR.
The configmaps required for this test have already been created in the "build-gcp-oracle-team" GKE build cluster.
Internal bug: b/417504312

Add a test case for single-instance setup on BMS

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

This PR updates the Pods specs to use separate SSH keys for RAC and single-instance setups.
This change provides a safety mechanism to reduce the risk of accidentally connecting to the wrong BMS machine. It also makes it harder for someone with access to one machine to connect to others.

Use different SSH keys for RAC and single-instance setup

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

I've found it isn't completing in the original 30 minute window so I'm going to bump it to 1 hour, with another hour inbetween runs. I don't think this needed to run hourly.

Update cadence and timeout for cleanerupper

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

There's no reason we can't push it all the way until almost the next run.

Update cleanerupper timeout to 1h45m

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

The Ansible linter's default rule set has a number of rules we don't follow, such as maximum line length.  As its warnings are just being ignored for now, let's remove it, pending more work on fine-tuning the rules.

Remove ansible linter from oracle-toolkit

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/legacy-periodics.yaml

Splits the existing job into 3 logical groups:
1. Compute image test pools
2. osconfig projects
3. CEP projects
Also removes the metadata scanner project which was turned down in 2023. Updates tab names and grouping to be clear around the new structure.

Update cleanerupper prow jobs to be more scoped down

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Activate the single-instance on gcp test, which was previously disabled (`always_run: false`) while still under development. Now that it is now ready, they will run unconditionally for all PRs.

set always_run to true and remove skip_report for single-instance-on-gcp test

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Updated the Prow job config to run the single-instance test using the new command:
`./presubmit_tests/gcp-test-runner.sh single-instance` instead of the old script.
Added a new presubmit job for testing two-node Data Guard deployment using the same test runner script with th appropriate parameter.
A follow-up PR will rename `./presubmit_tests/single-instance-on-gcp.sh` to `gcp-test-runner.sh` in the https://github.com/google/oracle-toolkit repo. This change will consolidate all GCP test logic into one script that supports multiple test types through parameters.

Add Data Guard test and update Prow job to use gcp-test-runner.sh 

---

prow/prowjobs/google/oracle-toolkit/oracle-toolkit-presubmit.yaml

Adding new test, with code from https://github.com/google/oracle-toolkit/pull/336
Not running or reporting by default, until the underlying PR is submitted and stable.

Add free edition test to oracle-toolkit-presubmit.yaml

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

They were timing out at 5, so this should give some leeway

Bump concurrency for rocky dev tests to 10

---

prow/prowjobs/GoogleContainerTools/kpt-config-sync/kpt-config-sync-periodics.yaml

There are currently no tests that run as part of https://testgrid.corp.google.com/googleoss-kpt-config-sync-main#standard-regular-gcenode. This change adds the required repository configs to enable the gcenode tests

Set required env vars for gcenode

---

prow/prowjobs/GoogleCloudPlatform/gcp-guest/gcp-guest-config.yaml

Increase the test timeout for cit-periodics-accelerator-images-accelerator-tests-a3u and cit-periodics-accelerator-images-accelerator-tests-a4 to 30 minutes from the default 20 minutes
This is to fix the timeouts in https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics-accelerator-images-accelerator-tests-a3u.

Increase test timeout for CIT A3U and A4 rdma tests.
